apiVersion: v1
kind: Service
metadata:
  name: synth-frontend-svc
  namespace: syntera-mvp
spec:
  selector:
    app: synth-frontend
  ports:
    - name: http
      port: 80
      targetPort: 5173
  type: ClusterIP