apiVersion: v1
kind: Service
metadata:
  name: synth-backend-svc
  namespace: syntera-mvp
spec:
  selector:
    app: synth-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
