// ════════════════════════════════════════════════════════════════════════════
// SpIcon — Design System Icon Component
// Generated from Figma export: Design_System_-_SP_icon
// 446 icons across 15 categories
//
// Categories & sample icons:

import React from 'react';
import './SpIcon.css';

// ── Icon name union type ──────────────────────────────────────────────────

export type SpIconName =
  "sp-Arrow-Arrow_Circle_Down" |
  "sp-Arrow-Arrow_Circle_Down_Left" |
  "sp-Arrow-Arrow_Circle_Down_Right" |
  "sp-Arrow-Arrow_Circle_Left" |
  "sp-Arrow-Arrow_Circle_Right" |
  "sp-Arrow-Arrow_Circle_Up" |
  "sp-Arrow-Arrow_Circle_Up_Left" |
  "sp-Arrow-Arrow_Circle_Up_Right" |
  "sp-Arrow-Arrow_Down_LG" |
  "sp-Arrow-Arrow_Down_Left_LG" |
  "sp-Arrow-Arrow_Down_Left_MD" |
  "sp-Arrow-Arrow_Down_Left_SM" |
  "sp-Arrow-Arrow_Down_MD" |
  "sp-Arrow-Arrow_Down_Right_LG" |
  "sp-Arrow-Arrow_Down_Right_MD" |
  "sp-Arrow-Arrow_Down_Right_SM" |
  "sp-Arrow-Arrow_Down_SM" |
  "sp-Arrow-Arrow_Down_Up" |
  "sp-Arrow-Arrow_Left_LG" |
  "sp-Arrow-Arrow_Left_MD" |
  "sp-Arrow-Arrow_Left_Right" |
  "sp-Arrow-Arrow_Left_SM" |
  "sp-Arrow-Arrow_Reload_02" |
  "sp-Arrow-Arrow_Right_LG" |
  "sp-Arrow-Arrow_Right_MD" |
  "sp-Arrow-Arrow_Right_SM" |
  "sp-Arrow-Arrow_Sub_Down_Left" |
  "sp-Arrow-Arrow_Sub_Down_Right" |
  "sp-Arrow-Arrow_Sub_Left_Down" |
  "sp-Arrow-Arrow_Sub_Left_Up" |
  "sp-Arrow-Arrow_Sub_Right_Down" |
  "sp-Arrow-Arrow_Sub_Right_Up" |
  "sp-Arrow-Arrow_Sub_Up_Left" |
  "sp-Arrow-Arrow_Sub_Up_Right" |
  "sp-Arrow-Arrow_Undo_Down_Left" |
  "sp-Arrow-Arrow_Undo_Down_Right" |
  "sp-Arrow-Arrow_Undo_Up_Left" |
  "sp-Arrow-Arrow_Undo_Up_Right" |
  "sp-Arrow-Arrow_Up_LG" |
  "sp-Arrow-Arrow_Up_Left_LG" |
  "sp-Arrow-Arrow_Up_Left_MD" |
  "sp-Arrow-Arrow_Up_Left_SM" |
  "sp-Arrow-Arrow_Up_MD" |
  "sp-Arrow-Arrow_Up_Right_LG" |
  "sp-Arrow-Arrow_Up_Right_MD" |
  "sp-Arrow-Arrow_Up_Right_SM" |
  "sp-Arrow-Arrow_Up_SM" |
  "sp-Arrow-Arrows_Reload_01" |
  "sp-Arrow-Caret_Circle_Down" |
  "sp-Arrow-Caret_Circle_Left" |
  "sp-Arrow-Caret_Circle_Right" |
  "sp-Arrow-Caret_Circle_Up" |
  "sp-Arrow-Caret_Down_MD" |
  "sp-Arrow-Caret_Down_SM" |
  "sp-Arrow-Caret_Left_SM" |
  "sp-Arrow-Caret_Right_SM" |
  "sp-Arrow-Caret_Up_MD" |
  "sp-Arrow-Caret_Up_SM" |
  "sp-Arrow-Chevron_Down" |
  "sp-Arrow-Chevron_Down_Duo" |
  "sp-Arrow-Chevron_Left" |
  "sp-Arrow-Chevron_Left_Duo" |
  "sp-Arrow-Chevron_Left_MD" |
  "sp-Arrow-Chevron_Right" |
  "sp-Arrow-Chevron_Right_Duo" |
  "sp-Arrow-Chevron_Right_MD" |
  "sp-Arrow-Chevron_Up" |
  "sp-Arrow-Chevron_Up_Duo" |
  "sp-Arrow-Expand" |
  "sp-Arrow-Shrink" |
  "sp-Arrow-Unfold_Less" |
  "sp-Arrow-Unfold_More" |
  "sp-Calendar-Alarm" |
  "sp-Calendar-Calendar" |
  "sp-Calendar-Calendar_Add" |
  "sp-Calendar-Calendar_Check" |
  "sp-Calendar-Calendar_Close" |
  "sp-Calendar-Calendar_Days" |
  "sp-Calendar-Calendar_Event" |
  "sp-Calendar-Calendar_Remove" |
  "sp-Calendar-Calendar_Week" |
  "sp-Calendar-Clock" |
  "sp-Calendar-Timer" |
  "sp-Calendar-Timer_Add" |
  "sp-Calendar-Timer_Close" |
  "sp-Calendar-Timer_Remove" |
  "sp-Communication-Bell" |
  "sp-Communication-Bell_Add" |
  "sp-Communication-Bell_Close" |
  "sp-Communication-Bell_Notification" |
  "sp-Communication-Bell_Off" |
  "sp-Communication-Bell_Remove" |
  "sp-Communication-Bell_Ring" |
  "sp-Communication-Chat" |
  "sp-Communication-Chat_Add" |
  "sp-Communication-Chat_Check" |
  "sp-Communication-Chat_Circle" |
  "sp-Communication-Chat_Circle_Add" |
  "sp-Communication-Chat_Circle_Check" |
  "sp-Communication-Chat_Circle_Close" |
  "sp-Communication-Chat_Circle_Dots" |
  "sp-Communication-Chat_Circle_Remove" |
  "sp-Communication-Chat_Close" |
  "sp-Communication-Chat_Conversation" |
  "sp-Communication-Chat_Conversation_Circle" |
  "sp-Communication-Chat_Dots" |
  "sp-Communication-Chat_Remove" |
  "sp-Communication-Mail" |
  "sp-Communication-Mail_Open" |
  "sp-Communication-Paper_Plane" |
  "sp-Communication-Phone" |
  "sp-Communication-Share_Android" |
  "sp-Communication-Share_iOS_Export" |
  "sp-Edit-Add_Column" |
  "sp-Edit-Add_Minus_Square" |
  "sp-Edit-Add_Plus" |
  "sp-Edit-Add_Plus_Circle" |
  "sp-Edit-Add_Plus_Square" |
  "sp-Edit-Add_Row" |
  "sp-Edit-Add_To_Queue" |
  "sp-Edit-Bold" |
  "sp-Edit-Close_Circle" |
  "sp-Edit-Close_Square" |
  "sp-Edit-Columns" |
  "sp-Edit-Combine_Cells" |
  "sp-Edit-Copy" |
  "sp-Edit-Crop" |
  "sp-Edit-Delete_Column" |
  "sp-Edit-Delete_Row" |
  "sp-Edit-Double_Quotes_L" |
  "sp-Edit-Double_Quotes_R" |
  "sp-Edit-Edit_Pencil_01" |
  "sp-Edit-Edit_Pencil_02" |
  "sp-Edit-Edit_Pencil_Line_01" |
  "sp-Edit-Edit_Pencil_Line_02" |
  "sp-Edit-Figma" |
  "sp-Edit-Font" |
  "sp-Edit-Heading" |
  "sp-Edit-Heading_H1" |
  "sp-Edit-Heading_H2" |
  "sp-Edit-Heading_H3" |
  "sp-Edit-Heading_H4" |
  "sp-Edit-Heading_H5" |
  "sp-Edit-Heading_H6" |
  "sp-Edit-Hide" |
  "sp-Edit-Italic" |
  "sp-Edit-Layer" |
  "sp-Edit-Layers" |
  "sp-Edit-List_Add" |
  "sp-Edit-List_Check" |
  "sp-Edit-List_Checklist" |
  "sp-Edit-List_Ordered" |
  "sp-Edit-List_Remove" |
  "sp-Edit-List_Unordered" |
  "sp-Edit-Mention" |
  "sp-Edit-Move" |
  "sp-Edit-Move_Horizontal" |
  "sp-Edit-Move_Vertical" |
  "sp-Edit-Paperclip_Attechment_Horizontal" |
  "sp-Edit-Paperclip_Attechment_Tilt" |
  "sp-Edit-Paragraph" |
  "sp-Edit-Path" |
  "sp-Edit-Redo" |
  "sp-Edit-Remove_Minus" |
  "sp-Edit-Remove_Minus_Circle" |
  "sp-Edit-Rows" |
  "sp-Edit-Ruler" |
  "sp-Edit-Select_Multiple" |
  "sp-Edit-Show" |
  "sp-Edit-Single_Quotes_L" |
  "sp-Edit-Single_Quotes_R" |
  "sp-Edit-Sort_Ascending" |
  "sp-Edit-Sort_Descending" |
  "sp-Edit-Strikethrough" |
  "sp-Edit-Swatches_Palette" |
  "sp-Edit-Table" |
  "sp-Edit-Table_Add" |
  "sp-Edit-Table_Remove" |
  "sp-Edit-Text" |
  "sp-Edit-Text_Align_Center" |
  "sp-Edit-Text_Align_Justify" |
  "sp-Edit-Text_Align_Left" |
  "sp-Edit-Text_Align_Right" |
  "sp-Edit-Underline" |
  "sp-Edit-Undo" |
  "sp-Environment-Bulb" |
  "sp-Environment-Coffe_To_Go" |
  "sp-Environment-Coffee" |
  "sp-Environment-Cookie" |
  "sp-Environment-Cupcake" |
  "sp-Environment-First_Aid" |
  "sp-Environment-Leaf" |
  "sp-Environment-Moon" |
  "sp-Environment-Planet" |
  "sp-Environment-Puzzle" |
  "sp-Environment-Rainbow" |
  "sp-Environment-Sun" |
  "sp-Environment-Water_Drop" |
  "sp-File-Archive" |
  "sp-File-Cloud" |
  "sp-File-Cloud_Add" |
  "sp-File-Cloud_Check" |
  "sp-File-Cloud_Close" |
  "sp-File-Cloud_Download" |
  "sp-File-Cloud_Off" |
  "sp-File-Cloud_Remove" |
  "sp-File-Cloud_Upload" |
  "sp-File-Download_Package" |
  "sp-File-File_Add" |
  "sp-File-File_Blank" |
  "sp-File-File_Check" |
  "sp-File-File_Close" |
  "sp-File-File_Code" |
  "sp-File-File_Document" |
  "sp-File-File_Download" |
  "sp-File-File_Edit" |
  "sp-File-File_Remove" |
  "sp-File-File_Search" |
  "sp-File-File_Upload" |
  "sp-File-Files" |
  "sp-File-Folder" |
  "sp-File-Folder_Add" |
  "sp-File-Folder_Check" |
  "sp-File-Folder_Close" |
  "sp-File-Folder_Code" |
  "sp-File-Folder_Document" |
  "sp-File-Folder_Download" |
  "sp-File-Folder_Edit" |
  "sp-File-Folder_Open" |
  "sp-File-Folder_Remove" |
  "sp-File-Folder_Search" |
  "sp-File-Folder_Upload" |
  "sp-File-Folders" |
  "sp-File-Note" |
  "sp-File-Note_Edit" |
  "sp-File-Note_Search" |
  "sp-File-Notebook" |
  "sp-Interface-Book" |
  "sp-Interface-Book_Open" |
  "sp-Interface-Bookmark" |
  "sp-Interface-Chart_Bar_Horizontal_01" |
  "sp-Interface-Chart_Bar_Vertical_01" |
  "sp-Interface-Chart_Line" |
  "sp-Interface-Chart_Pie" |
  "sp-Interface-Check" |
  "sp-Interface-Check_All" |
  "sp-Interface-Check_All_Big" |
  "sp-Interface-Check_Big" |
  "sp-Interface-Checkbox_Check" |
  "sp-Interface-Checkbox_Fill" |
  "sp-Interface-Checkbox_Unchecked" |
  "sp-Interface-Command" |
  "sp-Interface-Credit_Card_01" |
  "sp-Interface-Credit_Card_02" |
  "sp-Interface-Download" |
  "sp-Interface-Drag_Horizontal" |
  "sp-Interface-Drag_Vertical" |
  "sp-Interface-Dummy_Circle" |
  "sp-Interface-Dummy_Circle_Small" |
  "sp-Interface-Dummy_Square" |
  "sp-Interface-Dummy_Square_Small" |
  "sp-Interface-Exit" |
  "sp-Interface-External_Link" |
  "sp-Interface-Filter" |
  "sp-Interface-Filter_Off" |
  "sp-Interface-Gift" |
  "sp-Interface-Handbag" |
  "sp-Interface-Heart_01" |
  "sp-Interface-Heart_02" |
  "sp-Interface-Instance" |
  "sp-Interface-Label" |
  "sp-Interface-Line_L" |
  "sp-Interface-Line_M" |
  "sp-Interface-Line_S" |
  "sp-Interface-Line_Xl" |
  "sp-Interface-Link" |
  "sp-Interface-Link_Break" |
  "sp-Interface-Link_Horizontal" |
  "sp-Interface-Link_Horizontal_Off" |
  "sp-Interface-Link_Vertical" |
  "sp-Interface-Loading" |
  "sp-Interface-Lock" |
  "sp-Interface-Lock_Open" |
  "sp-Interface-Log_Out" |
  "sp-Interface-Magnifying_Glass_Minus" |
  "sp-Interface-Magnifying_Glass_Plus" |
  "sp-Interface-Main_Component" |
  "sp-Interface-Option" |
  "sp-Interface-Radio_Fill" |
  "sp-Interface-Radio_Unchecked" |
  "sp-Interface-Search_Magnifying_Glass" |
  "sp-Interface-Settings" |
  "sp-Interface-Settings_Future" |
  "sp-Interface-Shopping_Bag_01" |
  "sp-Interface-Shopping_Bag_02" |
  "sp-Interface-Shopping_Cart_01" |
  "sp-Interface-Shopping_Cart_02" |
  "sp-Interface-Slider_01" |
  "sp-Interface-Slider_02" |
  "sp-Interface-Slider_03" |
  "sp-Interface-Star" |
  "sp-Interface-Suitcase" |
  "sp-Interface-Swicht_Left" |
  "sp-Interface-Swicht_Right" |
  "sp-Interface-Tag" |
  "sp-Interface-Ticket_Voucher" |
  "sp-Interface-Trash_Empty" |
  "sp-Interface-Trash_Full" |
  "sp-Interface-Trending_Down" |
  "sp-Interface-Trending_Up" |
  "sp-Media-Airplay" |
  "sp-Media-Chromecast" |
  "sp-Media-Forward" |
  "sp-Media-Headphones" |
  "sp-Media-Image_01" |
  "sp-Media-Image_02" |
  "sp-Media-Pause" |
  "sp-Media-Pause_Circle" |
  "sp-Media-Play" |
  "sp-Media-Play_Circle" |
  "sp-Media-Rewind" |
  "sp-Media-Shuffle" |
  "sp-Media-Skip_Back" |
  "sp-Media-Skip_Forward" |
  "sp-Media-Stop" |
  "sp-Media-Stop_Circle" |
  "sp-Media-Volume_Max" |
  "sp-Media-Volume_Min" |
  "sp-Media-Volume_Minus" |
  "sp-Media-Volume_Off" |
  "sp-Media-Volume_Off_02" |
  "sp-Media-Volume_Plus" |
  "sp-Menu-Close_LG" |
  "sp-Menu-Close_MD" |
  "sp-Menu-Close_SM" |
  "sp-Menu-Hamburger_LG" |
  "sp-Menu-Hamburger_MD" |
  "sp-Menu-Menu_Alt_01" |
  "sp-Menu-Menu_Alt_02" |
  "sp-Menu-Menu_Alt_03" |
  "sp-Menu-Menu_Alt_04" |
  "sp-Menu-Menu_Alt_05" |
  "sp-Menu-Menu_Duo_LG" |
  "sp-Menu-Menu_Duo_MD" |
  "sp-Menu-More_Grid_Big" |
  "sp-Menu-More_Grid_Small" |
  "sp-Menu-More_Horizontal" |
  "sp-Menu-More_Vertical" |
  "sp-Navigation-Building_01" |
  "sp-Navigation-Building_02" |
  "sp-Navigation-Building_03" |
  "sp-Navigation-Building_04" |
  "sp-Navigation-Car_Auto" |
  "sp-Navigation-Compass" |
  "sp-Navigation-Flag" |
  "sp-Navigation-Globe" |
  "sp-Navigation-House_01" |
  "sp-Navigation-House_02" |
  "sp-Navigation-House_03" |
  "sp-Navigation-House_Add" |
  "sp-Navigation-House_Check" |
  "sp-Navigation-House_Close" |
  "sp-Navigation-House_Remove" |
  "sp-Navigation-Map" |
  "sp-Navigation-Map_Pin" |
  "sp-Navigation-Navigation" |
  "sp-Other-Dashboard" |
  "sp-Other-Logout" |
  "sp-Other-Magic" |
  "sp-Other-Mic" |
  "sp-Shape-Circle" |
  "sp-Shape-Octagon" |
  "sp-Shape-Shield" |
  "sp-Shape-Square" |
  "sp-Shape-Triangle" |
  "sp-Shape-Wavy" |
  "sp-System-Bar_Bottom" |
  "sp-System-Bar_Left" |
  "sp-System-Bar_Right" |
  "sp-System-Bar_Top" |
  "sp-System-Camera" |
  "sp-System-Code" |
  "sp-System-Cylinder" |
  "sp-System-Data" |
  "sp-System-Desktop" |
  "sp-System-Desktop_Tower" |
  "sp-System-Devices" |
  "sp-System-Keyboard" |
  "sp-System-Laptop" |
  "sp-System-Mobile" |
  "sp-System-Mobile_Button" |
  "sp-System-Monitor" |
  "sp-System-Monitor_Play" |
  "sp-System-Mouse" |
  "sp-System-Moving_Desk" |
  "sp-System-Printer" |
  "sp-System-Qr_Code" |
  "sp-System-Save" |
  "sp-System-Tablet" |
  "sp-System-Tablet_Button" |
  "sp-System-Terminal" |
  "sp-System-Wifi_High" |
  "sp-System-Wifi_Low" |
  "sp-System-Wifi_Medium" |
  "sp-System-Wifi_None" |
  "sp-System-Wifi_Off" |
  "sp-System-Wifi_Problem" |
  "sp-System-Window" |
  "sp-System-Window_Check" |
  "sp-System-Window_Close" |
  "sp-System-Window_Code_Block" |
  "sp-System-Window_Sidebar" |
  "sp-System-Window_Terminal" |
  "sp-User-User_01" |
  "sp-User-User_02" |
  "sp-User-User_03" |
  "sp-User-User_Add" |
  "sp-User-User_Card_ID" |
  "sp-User-User_Check" |
  "sp-User-User_Circle" |
  "sp-User-User_Close" |
  "sp-User-User_Remove" |
  "sp-User-User_Square" |
  "sp-User-User_Voice" |
  "sp-User-Users" |
  "sp-User-Users_Group" |
  "sp-Warning-Circle_Check" |
  "sp-Warning-Circle_Help" |
  "sp-Warning-Circle_Warning" |
  "sp-Warning-Help" |
  "sp-Warning-Info" |
  "sp-Warning-Octagon_Check" |
  "sp-Warning-Octagon_Help" |
  "sp-Warning-Octagon_Warning" |
  "sp-Warning-Shield_Check" |
  "sp-Warning-Shield_Warning" |
  "sp-Warning-Square_Check" |
  "sp-Warning-Square_Help" |
  "sp-Warning-Square_Warning" |
  "sp-Warning-Stop_Sign" |
  "sp-Warning-Triangle_Check" |
  "sp-Warning-Triangle_Warning" |
  "sp-Warning-Warning" |
  "sp-Warning-Wavy_Check" |
  "sp-Warning-Wavy_Help" |
  "sp-Warning-Wavy_Warning";

// ── Props ─────────────────────────────────────────────────────────────────

export interface SpIconProps {
  /** The icon ID — e.g. "sp-Arrow-Chevron_Down", "sp-User-User_Check" */
  name: SpIconName;
  /** Size in px — applied to both width and height. Default: 20 */
  size?: number;
  /** CSS color for strokes and fills. Defaults to currentColor (inherits from parent) */
  color?: string;
  /** Extra className for custom overrides */
  className?: string;
  /** Accessible label. Omit to hide from screen readers (decorative icon) */
  label?: string;
  style?: React.CSSProperties;
}

// ── Component ─────────────────────────────────────────────────────────────

const SpIcon: React.FC<SpIconProps> = ({
  name,
  size = 20,
  color,
  className = '',
  label,
  style,
}) => (
  <svg
    width={size}
    height={size}
    aria-label={label}
    aria-hidden={label === undefined ? true : undefined}
    className={`sp-icon${className ? ` ${className}` : ''}`}
    style={{ color, flexShrink: 0, ...style }}
  >
    <use href={`#${name}`} />
  </svg>
);

export default SpIcon;