// hooks/usePersonaBuilder.js
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { personaService } from '../services/personaService';

// Keys for queries
export const personaKeys = {
  all: ['personas'],
  lists: () => [...personaKeys.all, 'list'],
  list: (workspaceId, objectiveId) =>
    [...personaKeys.lists(), { workspaceId, objectiveId }],
  listGenerated: (workspaceId, objectiveId) =>
    [...personaKeys.lists(), { workspaceId, objectiveId }, 'generated'],
  details: () => [...personaKeys.all, 'detail'],
  detail: (workspaceId, objectiveId, personaId) =>
    [...personaKeys.details(), { workspaceId, objectiveId, personaId }],
  preview: (workspaceId, objectiveId, personaId) =>
    [...personaKeys.all, 'preview', { workspaceId, objectiveId, personaId }],
  validation: (objectiveId, traitGroup) =>
    [...personaKeys.all, 'validation', { objectiveId, traitGroup }],
};

// Custom hooks
export const usePersonas = (workspaceId, objectiveId, options = {}) => {
  return useQuery({
    queryKey: personaKeys.list(workspaceId, objectiveId),
    queryFn: () => personaService.getPersonas(workspaceId, objectiveId),
    enabled: !!(workspaceId && objectiveId),
    ...options,
  });
};

export const useAutoGeneratePersonas = (workspaceId, objectiveId, options = {}) => {
  return useQuery({
    queryKey: personaKeys.listGenerated(workspaceId, objectiveId),
    queryFn: () => personaService.getAutoGeneratedPersonas(workspaceId, objectiveId),
    enabled: !!(workspaceId && objectiveId),
    ...options,
  });
};

export const usePersona = (workspaceId, objectiveId, personaId, options = {}) => {
  return useQuery({
    queryKey: personaKeys.detail(workspaceId, objectiveId, personaId),
    queryFn: () => personaService.getPersona(workspaceId, objectiveId, personaId),
    enabled: !!(workspaceId && objectiveId && personaId),
    ...options,
  });
};

export const useSubmitCompletePersona = (workspaceId, objectiveId) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data) => personaService.submitCompletePersona(workspaceId, objectiveId, data),
    onSuccess: (newPersona) => {
      // Invalidate and refetch
      queryClient.invalidateQueries({
        queryKey: personaKeys.list(workspaceId, objectiveId),
      });
      return newPersona;
    },
  });
};

export const useUpdatePersona = (workspaceId, objectiveId, personaId) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data) => personaService.updatePersona(workspaceId, objectiveId, personaId, data),
    onSuccess: (updatedPersona) => {
      // Update cache
      queryClient.setQueryData(
        personaKeys.detail(workspaceId, objectiveId, personaId),
        updatedPersona
      );
      queryClient.invalidateQueries({
        queryKey: personaKeys.list(workspaceId, objectiveId),
      });
      queryClient.invalidateQueries({
        queryKey: personaKeys.preview(workspaceId, objectiveId, personaId),
      });
      return updatedPersona;
    },
  });
};

export const useDeletePersona = (workspaceId, objectiveId) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (personaId) => personaService.deletePersona(workspaceId, objectiveId, personaId),
    onSuccess: (_, personaId) => {
      // Remove from cache
      queryClient.removeQueries({
        queryKey: personaKeys.detail(workspaceId, objectiveId, personaId),
      });
      queryClient.invalidateQueries({
        queryKey: personaKeys.list(workspaceId, objectiveId),
      });
    },
  });
};

export const usePersonaPreview = (workspaceId, objectiveId, personaId, options = {}) => {
  return useQuery({
    queryKey: personaKeys.preview(workspaceId, objectiveId, personaId),
    queryFn: () => personaService.getPersonaPreview(workspaceId, objectiveId, personaId),
    enabled: !!(workspaceId && objectiveId && personaId),
    ...options,
  });
};

export const useValidateTraits = () => {
  return useMutation({
    mutationFn: ({ objectiveId, traitGroup, traits }) =>
      personaService.validateTraits(objectiveId, traitGroup, traits),
  });
};

export const usePersonaBuilder = (workspaceId, objectiveId) => {
  const personasQuery = usePersonas(workspaceId, objectiveId);
  const submitCompletePersonaMutation = useSubmitCompletePersona(workspaceId, objectiveId);
  const validateTraitsMutation = useValidateTraits();

  return {
    personas: personasQuery.data,
    isLoading: personasQuery.isLoading,
    error: personasQuery.error,
    refetchPersonas: personasQuery.refetch,
    submitCompletePersona: submitCompletePersonaMutation.mutateAsync,
    isSubmitting: submitCompletePersonaMutation.isPending,
    validateTraits: validateTraitsMutation.mutateAsync,
    isValidating: validateTraitsMutation.isPending,
    validationResult: validateTraitsMutation.data,
  };
};