// hooks/usePersonaBuilder.js
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { personaService } from '../services/personaService';

// Keys for queries
export const personaKeys = {
  all: ['personas'],
  lists: () => [...personaKeys.all, 'list'],
  list: (workspaceId, objectiveId) =>
    [...personaKeys.lists(), { workspaceId, objectiveId }],
  quota: (workspaceId, objectiveId) =>
    [...personaKeys.all, 'quota', { workspaceId, objectiveId }],
  listGenerated: (workspaceId, objectiveId) =>
    [...personaKeys.lists(), { workspaceId, objectiveId }, 'generated'],
  details: () => [...personaKeys.all, 'detail'],
  detail: (workspaceId, objectiveId, personaId) =>
    [...personaKeys.details(), { workspaceId, objectiveId, personaId }],
  preview: (workspaceId, objectiveId, personaId) =>
    [...personaKeys.all, 'preview', { workspaceId, objectiveId, personaId }],
  validation: (objectiveId, traitGroup) =>
    [...personaKeys.all, 'validation', { objectiveId, traitGroup }],
};

// Custom hooks
export const usePersonas = (workspaceId, objectiveId, options = {}) => {
  return useQuery({
    queryKey: personaKeys.list(workspaceId, objectiveId),
    queryFn: () => personaService.getPersonas(workspaceId, objectiveId),
    enabled: !!(workspaceId && objectiveId),
    ...options,
  });
};

export const useAutoGeneratePersonas = (workspaceId, objectiveId, options = {}) => {
  return useQuery({
    queryKey: personaKeys.listGenerated(workspaceId, objectiveId),
    queryFn: () => personaService.getAutoGeneratedPersonas(workspaceId, objectiveId),
    enabled: !!(workspaceId && objectiveId),
    ...options,
  });
};

export const usePersonaQuota = (workspaceId, objectiveId, options = {}) => {
  return useQuery({
    queryKey: personaKeys.quota(workspaceId, objectiveId),
    queryFn: () => personaService.getPersonaQuota(workspaceId, objectiveId),
    enabled: !!(workspaceId && objectiveId),
    ...options,
  });
};

export const usePersona = (workspaceId, objectiveId, personaId, options = {}) => {
  return useQuery({
    queryKey: personaKeys.detail(workspaceId, objectiveId, personaId),
    queryFn: () => personaService.getPersona(workspaceId, objectiveId, personaId),
    enabled: !!(workspaceId && objectiveId && personaId),
    ...options,
  });
};

export const useSubmitCompletePersona = (workspaceId, objectiveId) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data) => personaService.submitCompletePersona(workspaceId, objectiveId, data),
    onSuccess: (newPersona) => {
      // Invalidate and refetch
      queryClient.invalidateQueries({
        queryKey: personaKeys.list(workspaceId, objectiveId),
      });
      return newPersona;
    },
  });
};

export const useUpdatePersona = (workspaceId, objectiveId, personaId) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data) => personaService.updatePersona(workspaceId, objectiveId, personaId, data),
    onSuccess: (updatedPersona) => {
      // Update cache
      queryClient.setQueryData(
        personaKeys.detail(workspaceId, objectiveId, personaId),
        updatedPersona
      );
      queryClient.invalidateQueries({
        queryKey: personaKeys.list(workspaceId, objectiveId),
      });
      queryClient.invalidateQueries({
        queryKey: personaKeys.preview(workspaceId, objectiveId, personaId),
      });
      return updatedPersona;
    },
  });
};

export const useDeletePersona = (workspaceId, objectiveId) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (personaId) => personaService.deletePersona(workspaceId, objectiveId, personaId),
    onSuccess: (_, personaId) => {
      // Remove from cache
      queryClient.removeQueries({
        queryKey: personaKeys.detail(workspaceId, objectiveId, personaId),
      });
      queryClient.invalidateQueries({
        queryKey: personaKeys.list(workspaceId, objectiveId),
      });
    },
  });
};

export const usePersonaPreview = (workspaceId, objectiveId, personaId, options = {}) => {
  return useQuery({
    queryKey: personaKeys.preview(workspaceId, objectiveId, personaId),
    queryFn: () => personaService.getPersonaPreview(workspaceId, objectiveId, personaId),
    enabled: !!(workspaceId && objectiveId && personaId),
    // Knowledge Enrichment (enrich_persona_ke_sources) runs as a
    // fire-and-forget background task AFTER persona generation/calibration's
    // HTTP response already returned, so the very first preview fetch — made
    // right after generation, which is the normal "review your persona" flow
    // — can land before that background task has patched
    // persona_details.ke_evidence_coverage into the DB. Without polling, the
    // Evidence Sources modal falls back to a random client-side placeholder
    // ("Platforms and communities...") forever, even though the real
    // Knowledge Enrichment data exists moments later — same "poll until the
    // async job's data lands" pattern already used by useQuestionnaires in
    // useQuantitativeQueries.ts. Stops as soon as ke_evidence_coverage is
    // present, is never started for draft (not-yet-calibrated) personas
    // (KE hasn't run yet by design), and gives up after 3 minutes so a
    // persona that genuinely never gets KE data (e.g. a provider outage)
    // doesn't poll forever. 3 minutes, not 90s, because the web-search
    // fallback step alone was measured taking up to ~86s in a live run
    // (Anthropic web_search across up to 6 batched queries) — a tighter
    // cutoff risked giving up moments before real data actually landed.
    refetchInterval: (query) => {
      const traits = query.state.data?.data?.traits;
      if (!traits || traits.ke_evidence_coverage) return false;
      if (traits.calibration_status === 'draft') return false;
      const createdAtMs = traits.created_at ? new Date(traits.created_at).getTime() : null;
      if (createdAtMs && Date.now() - createdAtMs > 180_000) return false;
      return 4_000;
    },
    ...options,
  });
};

export const useValidateTraits = () => {
  return useMutation({
    mutationFn: ({ objectiveId, traitGroup, traits }) =>
      personaService.validateTraits(objectiveId, traitGroup, traits),
  });
};

export const useRealtimePlausibility = (workspaceId, objectiveId) => {
  return useMutation({
    mutationFn: (manualPersonaPayload) =>
      personaService.validatePersonaPlausibility(workspaceId, objectiveId, manualPersonaPayload),
  });
};

export const usePersonaBuilder = (workspaceId, objectiveId) => {
  const personasQuery = usePersonas(workspaceId, objectiveId);
  const quotaQuery = usePersonaQuota(workspaceId, objectiveId);
  const submitCompletePersonaMutation = useSubmitCompletePersona(workspaceId, objectiveId);
  const validateTraitsMutation = useValidateTraits();

  return {
    personas: personasQuery.data,
    isLoading: personasQuery.isLoading,
    error: personasQuery.error,
    refetchPersonas: personasQuery.refetch,
    personaQuota: quotaQuery.data,
    refetchPersonaQuota: quotaQuery.refetch,
    submitCompletePersona: submitCompletePersonaMutation.mutateAsync,
    isSubmitting: submitCompletePersonaMutation.isPending,
    validateTraits: validateTraitsMutation.mutateAsync,
    isValidating: validateTraitsMutation.isPending,
    validationResult: validateTraitsMutation.data,
  };
};
