// services/personaService.js
import axiosInstance from '../utils/axiosConfig';

export const personaService = {
  // Get persona templates
  getPersonaTemplates: async (workspaceId, objectiveId) => {
    const response = await axiosInstance.get(
      `/workspaces/${workspaceId}/research/objectives/${objectiveId}/personas/templates`
    );
    return response.data;
  },

  // Create a new persona
  createPersona: async (workspaceId, objectiveId, data) => {
    const response = await axiosInstance.post(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas`,
      data
    );
    return response.data;
  },

  // Get all personas for a research objective
  getPersonas: async (workspaceId, objectiveId) => {
    const response = await axiosInstance.get(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas`
    );
    return response.data;
  },

  getAutoGeneratedPersonas: async (workspaceId, objectiveId) => {
    const response = await axiosInstance.get(
      `workspaces/${workspaceId}/explorations/${objectiveId}/personas/auto-generate`
    );
    console.log("response.data => ", response.data);
    return response.data;
  },

  // Get a single persona by ID
  getPersona: async (workspaceId, objectiveId, personaId) => {
    const response = await axiosInstance.get(
      `/workspaces/${workspaceId}/research/objectives/${objectiveId}/personas/${personaId}`
    );
    return response.data;
  },

  // Update a persona
  updatePersona: async (workspaceId, objectiveId, personaId, data) => {
    const response = await axiosInstance.put(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas/${personaId}`,
      data
    );
    return response.data;
  },

  // Delete a persona
  deletePersona: async (workspaceId, objectiveId, personaId) => {
    const response = await axiosInstance.delete(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas/${personaId}`
    );
    return response.data;
  },

  // Get persona preview
  getPersonaPreview: async (workspaceId, objectiveId, personaId) => {
    const response = await axiosInstance.get(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas/${personaId}/preview`
    );
    return response.data;
  },

  // Validate persona traits
  validateTraits: async (objectiveId, traitGroup, traits) => {
    const response = await axiosInstance.post(
      `/workspaces/{workspace_id}/explorations/{exploration_id}/personas/traits_validation`,
      {
        exploration_id: objectiveId,
        trait_group: traitGroup,
        traits: traits
      }
    );
    return response.data;
  },
  submitCompletePersona: async (workspaceId, objectiveId, data) => {
    const response = await axiosInstance.post(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas/`,
      {
        ...data,
        exploration_id: objectiveId // Add exploration_id from objectiveId
      }
    );
    return response.data;
  },
};