// services/personaService.js
import axiosInstance from '../utils/axiosConfig';

export const personaService = {
  // Get persona templates
  getPersonaTemplates: async (workspaceId, objectiveId) => {
    const response = await axiosInstance.get(
      `/workspaces/${workspaceId}/research/objectives/${objectiveId}/personas/templates`
    );
    return response.data;
  },

  // Create a new persona
  createPersona: async (workspaceId, objectiveId, data) => {
    const response = await axiosInstance.post(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas`,
      data
    );
    return response.data;
  },

  // Get all personas for a research objective
  getPersonas: async (workspaceId, objectiveId) => {
    const response = await axiosInstance.get(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas`
    );
    return response.data;
  },

  getAutoGeneratedPersonas: async (workspaceId, objectiveId) => {
    const response = await axiosInstance.get(
      `workspaces/${workspaceId}/explorations/${objectiveId}/personas/auto-generate`
    );
    console.log("response.data => ", response.data);
    return response.data;
  },

  // Get a single persona by ID
  getPersona: async (workspaceId, objectiveId, personaId) => {
    const response = await axiosInstance.get(
      `/workspaces/${workspaceId}/research/objectives/${objectiveId}/personas/${personaId}`
    );
    return response.data;
  },

  // Update a persona
  updatePersona: async (workspaceId, objectiveId, personaId, data) => {
    const response = await axiosInstance.put(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas/${personaId}`,
      data
    );
    return response.data;
  },

  // Delete a persona
  deletePersona: async (workspaceId, objectiveId, personaId) => {
    const response = await axiosInstance.delete(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas/${personaId}`
    );
    return response.data;
  },

  downloadPersonaCards: async (workspaceId, objectiveId, personaIds) => {
    const response = await axiosInstance.post(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas/bulk-download`,
      { persona_ids: personaIds },
      { responseType: 'blob' }
    );
    return response.data;
  },

  replicatePersona: async (workspaceId, objectiveId, personaId, targetCountry) => {
    const response = await axiosInstance.post(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas/${personaId}/replicate`,
      { target_country: targetCountry }
    );
    return response.data;
  },

  // Get persona preview
  getPersonaPreview: async (workspaceId, objectiveId, personaId) => {
    const response = await axiosInstance.get(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas/${personaId}/preview`
    );
    return response.data;
  },

  // Legacy trait-group validator (tab-switching checks, separate backend route)
  validateTraits: async (workspaceId, objectiveId, traitGroup, traits) => {
    const response = await axiosInstance.post(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas/validate`,
      { trait_group: traitGroup, traits }
    );
    return response.data;
  },
  // Plausibility check — accepts full ManualPersonaCreate payload (nested shape)
  // Returns { data: { warnings[], has_warnings, can_proceed } }
  validatePersonaPlausibility: async (workspaceId, objectiveId, manualPersonaPayload) => {
    const response = await axiosInstance.post(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas/validate`,
      manualPersonaPayload
    );
    return response.data;
  },
  // Create manual persona draft — returns validation_warnings + has_plausibility_warnings
  submitCompletePersona: async (workspaceId, objectiveId, data) => {
    const response = await axiosInstance.post(
      `/workspaces/${workspaceId}/explorations/${objectiveId}/personas/manual`,
      data
    );
    return response.data;
  },
};
