"""Open-world city/region recognition, backed by a generated GeoNames extract.

WHY this exists: country recognition was made open-world (country_names.py,
all 249 ISO countries) but place recognition was not. Cities and regions were
recognised only if they appeared in a hand-written table covering eleven
countries, so the same user action resolved for some countries and failed for
the rest:

    ["Mumbai", "Pune"]        -> India      (Mumbai was in the table)
    ["Jakarta", "Surabaya"]   -> error      (Jakarta was not)

Both are a picker selection of cities with no country named. There is no
product reason for them to behave differently, and "add the missing country to
the table" is not a fix — it is the same bug waiting for the next country.
This module answers the question from data (app/data/geonames_places.json,
regenerated by scripts/generate_place_dataset.py), so no country is privileged
and none has to be added by hand.

What it deliberately does NOT do is guess. A name that several countries claim
comes back as a country only when one of them dominates the others by
DOMINANCE_RATIO; otherwise callers get the candidates and must ask the user.
"Valencia" is a real city in Venezuela and in Spain, and picking one for the
user is exactly the failure this whole path exists to prevent.

Depends only on country_names, so the modules that own the curated tables can
import it without a cycle.
"""

from __future__ import annotations

import json
import threading
from pathlib import Path

from app.services.country_names import iso_country_name, normalize_place

_DATASET_PATH = Path(__file__).resolve().parent.parent / "data" / "geonames_places.json"

# How much bigger the leading candidate must be before it counts as the
# obvious reading rather than a guess. Calibrated against the cases that
# actually occur: London (GB 8.9M / CA 422k = 21x) and Birmingham (GB 1.2M /
# US 196k = 5.9x) are what people mean; Valencia (VE 1.6M / ES 824k = 2.0x)
# and San José (US 997k / CR 335k = 3.0x) are not, and are worth one question
# to the user rather than a persona set in the wrong hemisphere.
DOMINANCE_RATIO = 3


_LOAD_LOCK = threading.Lock()
_LOADED: dict | None = None


def _dataset() -> dict:
    """Loaded once, on first use. Geography resolution is not on the hot path
    for most requests, so this stays lazy rather than costing every boot.

    Single-flight rather than a bare lru_cache: persona generation runs in a
    threadpool, so a cold process can take a dozen concurrent first calls, and
    each would otherwise parse and hold its own copy of the file at once.
    """
    global _LOADED
    if _LOADED is None:
        with _LOAD_LOCK:
            if _LOADED is None:
                with _DATASET_PATH.open(encoding="utf-8") as handle:
                    _LOADED = json.load(handle)
    return _LOADED


def _ranked_candidates(entry: str) -> list[tuple[str, int, int]]:
    """(country, weight, is_primary) for every country with a city OR region
    by this name — own-name claims first, then biggest first.

    Cities and regions are ranked together rather than one taking precedence
    over the other, because the two collide on names where only prominence
    tells them apart: "Bali" is a province of Indonesia (1.7M) and also a town
    in India (297k), and consulting cities first would answer India.
    """
    if not entry:
        return []
    key = normalize_place(entry)
    if not key:
        return []
    data = _dataset()
    merged: dict[str, tuple[int, int]] = {}
    for index in ("cities", "regions"):
        for country, weight, primary in data[index].get(key, []):
            previous_weight, previous_primary = merged.get(country, (0, 0))
            merged[country] = (max(weight, previous_weight), max(primary, previous_primary))
    return sorted(
        ((country, weight, primary) for country, (weight, primary) in merged.items()),
        key=lambda item: (-item[2], -item[1], item[0]),
    )


def place_country_candidates(entry: str) -> list[str]:
    """Every country that has a city or region by this name, most prominent
    first. Empty when the name is not in the gazetteer at all.

    Callers use this to tell the user what a name they picked could have
    meant, so they can say which one they meant.
    """
    return [country for country, _, _ in _ranked_candidates(entry)]


def resolve_place(entry: str) -> tuple[str, int] | None:
    """(country, prominence) for a place name, or None when it cannot be
    placed. Prominence is the population the ranking was decided on.

    Callers reading prose need the number: a name lifted out of a sentence is
    only worth trusting on its own if the place is unmistakable, and "Jakarta"
    (8.5M) and "Young" (a 15k town in Uruguay) are told apart by nothing else.
    """
    matches = _ranked_candidates(entry)
    country = resolve_place_country(entry)
    if country is None:
        return None
    return country, next(weight for name, weight, _ in matches if name == country)


def resolve_place_country(entry: str) -> str | None:
    """The country a place name belongs to, or None when the gazetteer does
    not know the name or cannot tell which country is meant.

    None is a legitimate, expected answer — callers treat it as "the user has
    to tell us", never as licence to fall back to some default country.
    """
    matches = _ranked_candidates(entry)
    if not matches:
        return None
    if len(matches) == 1:
        return matches[0][0]

    (top_country, top_weight, top_primary) = matches[0]
    (_, runner_up_weight, runner_up_primary) = matches[1]

    # A place called by its own name outranks a place that merely carries the
    # name as a historic or foreign alternate, however large the latter is:
    # Alexandria is Egypt's, not the Iranian city that Alexander also named.
    if top_primary > runner_up_primary:
        return top_country
    if runner_up_weight <= 0:
        return top_country
    if top_weight >= runner_up_weight * DOMINANCE_RATIO:
        return top_country
    return None


def country_city_pool(country: str) -> list[str]:
    """That country's largest cities, largest first, or [] if unknown.

    Used only as the fallback pool for spreading personas across a country the
    curated tables have no pool for. Accepts the user's own spelling — the ISO
    index folds "USA"/"United States of America" onto one canonical name, which
    is how the dataset is keyed.
    """
    if not country:
        return []
    canonical = iso_country_name(country) or country
    return _dataset()["city_pools"].get(canonical, [])
