"""
SyncDB scraping constants.
"""

import os

_ENV_BLOCKED = os.getenv("SYNCDB_BLOCKED_DOMAINS", "")
_ENV_SET = {item.strip().lower().removeprefix("www.") for item in _ENV_BLOCKED.split(",") if item.strip()}

PERMANENTLY_BLOCKED_DOMAINS: frozenset[str] = frozenset({
    "mckinsey.com",
    "oecd.org",
    "numerator.com",
    "untourism.int",
    "pwc.com",
    "pwc.in",
    "pwccn.com",
    "strategyand.pwc.com",
    "researchgate.net",
    "gartner.com",
    "iea.org",
    "weforum.org",
    "centres.weforum.org",
    "tripadvisor.com",
    "spglobal.com",
    "jdpower.com",
    "medallia.com",
    "swissre.com",
    "kearney.com",
    "bain.com",
    "cbre.com",
    "gsma.com",
    "thespacereport.org",
    "spacefoundation.org",
    "civicscience.com",
    "softwareadvice.com",
    "pro.morningconsult.com",
    "iap.unido.org",
    "intracen.org",
    "atlanticcouncil.org",
    "jbs.cam.ac.uk",
    "bankofengland.co.uk",
    "rba.gov.au",
    "health.govt.nz",
    "aihw.gov.au",
    "kingsfund.org.uk",
    "healthsystemtracker.org",
    "sermo.com",
    "pressganey.com",
    "info.pressganey.com",
    "westhealth.org",
    "content.naic.org",
    "tobaccoatlas.org",
    "cgap.org",
    "psa.gov.ph",
    "openstat.psa.gov.ph",
    "plasticseurope.org",
    "beyondpetrochemicals.org",
    "worldsteel.org",
    "icac.org",
    "saint-gobain.com",
    "onlinewhitepapers.com",
    "theconsumergoodsforum.com",
    "uitp.org",
    "airlines.org",
    "ahla.com",
    "dubaidet.gov.ae",
    "mmgy.com",
    "rics.org",
    "americas.uli.org",
    "knowledge.uli.org",
    "digital.cushmanwakefield.com",
    "ebu.ch",
    "cncf.io",
    "paloaltonetworks.com",
    "theesa.com",
    "alchemer.com",
    "deltek.com",
    "itu.int",
    "journals.sagepub.com",
    "ceew.in",
    "nrdc.org",
    "datainnovation.org",
    "opensignal.com",
    "isc2.org",
    "fico.com",
    "kpmg.com",
    "unitycg",
    "imf.org",
} | _ENV_SET)
