"""baseline: full existing schema

Generated by scripts/generate_baseline.py from a live database
(PostgreSQL 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)) on 2026-08-12T17:33:54.

THIS REVISION IS NEVER RUN AGAINST AN EXISTING DATABASE.

  * Databases that already have this schema (local, staging) are brought under
    Alembic control with `alembic stamp 0001_baseline`, which records the revision
    and executes nothing.
  * A brand-new database (production) runs `alembic upgrade head`, and this
    revision creates the schema in full.

Fidelity: every statement below was read from PostgreSQL's own catalog
formatters — format_type(), pg_get_expr(), pg_get_constraintdef() and
pg_indexes.indexdef — so types, defaults, partial-index predicates, expression
indexes, access methods and ON DELETE actions are reproduced exactly as they
exist today, including drift between SQLModel models and
app/migrations/startup.py. Reconciling that drift is deliberately left to later
revisions so that this one can be proven byte-equivalent to the current schema.

Verify with:
    python scripts/schema_inventory.py compare \
        --baseline-url $EXISTING_DB --candidate-url $SCRATCH_DB_AT_THIS_REVISION

Contents: 62 tables, 65 keys/checks,
86 foreign keys, 142 explicit indexes
(65 constraint-backing indexes omitted — they are
created implicitly by their constraint), 1 sequences,
1 functions, 1 triggers.

Revision ID: 0001_baseline
Revises: 
"""

from __future__ import annotations

from alembic import op

revision: str = '0001_baseline'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


SCHEMAS: tuple[str, ...] = ('sync_action', 'sync_source', 'sync_survey')

# Sequences come FIRST. A serial column's default is
# nextval('seq'::regclass), and PostgreSQL resolves that regclass cast when the
# table is created — so the sequence must already exist or CREATE TABLE fails.
SEQUENCES: tuple[str, ...] = (
    'CREATE SEQUENCE public.studies_id_seq AS integer START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 NO CYCLE',
)

CREATE_TABLES: tuple[str, ...] = (
    """CREATE TABLE public.artifact_pipeline_run (
    id character varying NOT NULL,
    workspace_id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    created_by character varying NOT NULL,
    artifact_type character varying NOT NULL,
    artifact_category character varying NOT NULL,
    comparison_mode character varying NOT NULL,
    num_assets integer NOT NULL,
    instruction text,
    ro_description text,
    source_file_ids json,
    persona_ids json,
    status character varying NOT NULL,
    error_stage character varying,
    error_message text,
    asset_dissections json,
    dimension_selection json,
    discussion_guide json,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    run_type character varying DEFAULT 'qual'::character varying NOT NULL
)""",
    """CREATE TABLE public.artifact_population_result (
    id character varying NOT NULL,
    run_id character varying NOT NULL,
    total_sample_size integer NOT NULL,
    personas_simulated json,
    results json,
    narrative json,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
)""",
    """CREATE TABLE public.billing_profile (
    id character varying NOT NULL,
    user_id character varying NOT NULL,
    org_id character varying,
    billing_name character varying,
    billing_email character varying,
    company_name character varying,
    gst_number character varying,
    address_line1 character varying,
    address_line2 character varying,
    city character varying,
    state character varying,
    country character varying,
    postal_code character varying,
    stripe_customer_id character varying,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone
)""",
    """CREATE TABLE public.decision_room_message (
    id character varying NOT NULL,
    session_id character varying NOT NULL,
    role character varying NOT NULL,
    content text,
    sequence_num integer NOT NULL,
    model_used character varying,
    token_input integer,
    token_output integer,
    cost_usd double precision,
    latency_ms integer,
    evidence json,
    stream_complete boolean NOT NULL,
    created_at timestamp without time zone
)""",
    """CREATE TABLE public.decision_room_session (
    id character varying NOT NULL,
    workspace_id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    flow character varying NOT NULL,
    title character varying,
    status character varying NOT NULL,
    context_rendered text,
    context_metadata json,
    prompt_version character varying NOT NULL,
    token_total_input integer NOT NULL,
    token_total_output integer NOT NULL,
    cost_usd_total double precision NOT NULL,
    created_by character varying NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
)""",
    """CREATE TABLE public.dp_analysis (
    id character varying NOT NULL,
    dataset_id character varying NOT NULL,
    analysis_type character varying NOT NULL,
    parameters jsonb,
    result jsonb,
    created_by character varying,
    created_at timestamp without time zone
)""",
    """CREATE TABLE public.dp_dataset (
    id character varying NOT NULL,
    workspace_id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    name character varying NOT NULL,
    original_filename character varying NOT NULL,
    stored_filename character varying NOT NULL,
    file_type character varying NOT NULL,
    row_count integer NOT NULL,
    column_count integer NOT NULL,
    status character varying NOT NULL,
    meta jsonb,
    created_by character varying,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
)""",
    """CREATE TABLE public.dp_variable (
    id character varying NOT NULL,
    dataset_id character varying NOT NULL,
    variable_name character varying NOT NULL,
    display_name character varying NOT NULL,
    data_type character varying NOT NULL,
    position integer NOT NULL,
    unique_values_count integer NOT NULL,
    missing_count integer NOT NULL,
    value_labels jsonb,
    meta jsonb,
    created_at timestamp without time zone
)""",
    """CREATE TABLE public.embedded_actions (
    action_id character varying NOT NULL,
    embedded_at timestamp without time zone DEFAULT now(),
    namespace character varying DEFAULT 'actions'::character varying
)""",
    """CREATE TABLE public.embedded_chunks (
    chunk_id character varying NOT NULL,
    embedded_at timestamp without time zone DEFAULT now(),
    namespace character varying DEFAULT 'hq_sources'::character varying
)""",
    """CREATE TABLE public.explorations (
    id character varying NOT NULL,
    workspace_id character varying NOT NULL,
    title character varying(255) NOT NULL,
    description character varying NOT NULL,
    clarification_attempts integer NOT NULL,
    is_quantitative boolean NOT NULL,
    is_qualitative boolean NOT NULL,
    created_by character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone,
    is_end boolean NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp without time zone,
    audience_type character varying DEFAULT 'B2C'::character varying NOT NULL,
    deleted_by character varying,
    updated_by character varying,
    additional_persona_limit integer DEFAULT 0 NOT NULL
)""",
    """CREATE TABLE public.interview (
    id character varying NOT NULL,
    workspace_id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    persona_id character varying,
    messages json,
    generated_answers json,
    created_by character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    session_group_id character varying
)""",
    """CREATE TABLE public.interviewfile (
    id character varying NOT NULL,
    interview_id character varying NOT NULL,
    filename character varying NOT NULL,
    original_name character varying NOT NULL,
    content_type character varying,
    size integer,
    uploaded_at timestamp without time zone NOT NULL
)""",
    """CREATE TABLE public.interviewquestion (
    id character varying NOT NULL,
    section_id character varying NOT NULL,
    text character varying NOT NULL,
    created_by character varying NOT NULL,
    created_at timestamp without time zone NOT NULL
)""",
    """CREATE TABLE public.interviewsection (
    id character varying NOT NULL,
    workspace_id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    title character varying NOT NULL,
    created_by character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    description character varying NOT NULL,
    is_download boolean NOT NULL
)""",
    """CREATE TABLE public.llm_usage_event (
    id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    workspace_id character varying,
    stage character varying NOT NULL,
    operation character varying,
    provider character varying NOT NULL,
    model character varying NOT NULL,
    input_tokens integer NOT NULL,
    output_tokens integer NOT NULL,
    cost_usd double precision,
    latency_ms integer,
    usage_raw jsonb,
    status character varying NOT NULL,
    error_message text,
    persona_id character varying,
    session_id character varying,
    request_id character varying,
    created_by character varying,
    created_at timestamp without time zone NOT NULL
)""",
    """CREATE TABLE public.market_research_extractions (
    id character varying NOT NULL,
    geography character varying(512),
    industry character varying(200),
    scenario text,
    created_at timestamp with time zone DEFAULT now(),
    result_data jsonb,
    publisher character varying(200),
    survey_id character varying(120)
)""",
    """CREATE TABLE public.omimessage (
    id character varying NOT NULL,
    session_id character varying NOT NULL,
    role character varying NOT NULL,
    content character varying NOT NULL,
    message_type character varying NOT NULL,
    workflow_stage character varying,
    omi_state character varying,
    created_at timestamp without time zone NOT NULL
)""",
    """CREATE TABLE public.omisession (
    id character varying NOT NULL,
    organization_id character varying NOT NULL,
    user_id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    workspace_id character varying,
    current_stage character varying NOT NULL,
    current_state character varying NOT NULL,
    context json,
    conversation_history json,
    completed_stages json,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    last_interaction timestamp without time zone NOT NULL
)""",
    """CREATE TABLE public.omiworkflowaction (
    id character varying NOT NULL,
    session_id character varying NOT NULL,
    action_type character varying NOT NULL,
    description character varying NOT NULL,
    status character varying NOT NULL,
    progress_percentage integer,
    started_at timestamp without time zone NOT NULL,
    completed_at timestamp without time zone,
    result json
)""",
    """CREATE TABLE public.org_settings (
    id character varying NOT NULL,
    org_id character varying NOT NULL,
    allowed_email_domains character varying NOT NULL,
    default_member_role character varying NOT NULL,
    enforce_sso boolean NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone
)""",
    """CREATE TABLE public.organization (
    id character varying NOT NULL,
    name character varying NOT NULL,
    owner_id character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    account_tier character varying DEFAULT 'standard'::character varying NOT NULL,
    exploration_limit integer DEFAULT 0 NOT NULL,
    exploration_count integer DEFAULT 0 NOT NULL,
    description text,
    logo_url character varying,
    domain character varying,
    industry character varying,
    website character varying
)""",
    """CREATE TABLE public.persona (
    id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    workspace_id character varying NOT NULL,
    name character varying NOT NULL,
    age_range character varying NOT NULL,
    gender character varying NOT NULL,
    location_country character varying NOT NULL,
    location_state character varying,
    education_level character varying NOT NULL,
    occupation character varying NOT NULL,
    income_range character varying NOT NULL,
    family_size character varying,
    geography character varying,
    lifestyle character varying,
    values character varying,
    personality character varying,
    interests jsonb,
    motivations character varying,
    brand_sensitivity character varying,
    price_sensitivity character varying,
    mobility character varying,
    accommodation character varying,
    marital_status character varying,
    daily_rhythm character varying,
    hobbies character varying,
    professional_traits character varying,
    digital_activity character varying,
    preferences character varying,
    created_by character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    backstory character varying,
    ocean_profile jsonb,
    persona_details jsonb,
    auto_generated_persona boolean,
    calibration_confidence integer,
    parent_persona_id character varying,
    calibration_status character varying,
    subject_key character varying,
    ml_domain character varying,
    master_calibration_confidence integer
)""",
    """CREATE TABLE public.persona_artifact_response (
    id character varying NOT NULL,
    run_id character varying NOT NULL,
    persona_id character varying NOT NULL,
    status character varying NOT NULL,
    response json,
    error_message text,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
)""",
    """CREATE TABLE public.populationsimulation (
    id character varying NOT NULL,
    workspace_id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    research_objective_id character varying NOT NULL,
    persona_ids json,
    sample_distribution json,
    persona_scores json,
    weighted_score double precision,
    global_insights json,
    created_by character varying NOT NULL,
    created_at timestamp without time zone NOT NULL
)""",
    """CREATE TABLE public.questionnairegenerationjob (
    id character varying NOT NULL,
    workspace_id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    simulation_id character varying,
    source_key character varying NOT NULL,
    status character varying NOT NULL,
    persona_ids json,
    error_message character varying,
    questionnaire_section_ids json,
    created_by character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    started_at timestamp without time zone,
    completed_at timestamp without time zone
)""",
    """CREATE TABLE public.questionnairequestion (
    id character varying NOT NULL,
    section_id character varying NOT NULL,
    text character varying NOT NULL,
    options json,
    created_by character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    question_type character varying DEFAULT 'S'::character varying NOT NULL,
    question_key character varying,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    order_index integer DEFAULT 0 NOT NULL
)""",
    """CREATE TABLE public.questionnairequestionasset (
    id character varying NOT NULL,
    question_id character varying NOT NULL,
    workspace_id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    filename character varying NOT NULL,
    original_name character varying NOT NULL,
    content_type character varying,
    size integer,
    asset_type character varying NOT NULL,
    metadata json,
    uploaded_by character varying NOT NULL,
    uploaded_at timestamp without time zone NOT NULL
)""",
    """CREATE TABLE public.questionnairesection (
    id character varying NOT NULL,
    workspace_id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    simulation_id character varying,
    title character varying NOT NULL,
    created_by character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    parent_section_id character varying,
    order_index integer DEFAULT 0 NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL
)""",
    """CREATE TABLE public.rebuttalsession (
    id character varying NOT NULL,
    workspace_id character varying NOT NULL,
    exploration_id character varying,
    persona_id character varying NOT NULL,
    simulation_id character varying,
    question_id character varying NOT NULL,
    starter_message character varying,
    messages json,
    user_message character varying,
    llm_response character varying,
    llm_metadata json,
    created_by character varying NOT NULL,
    created_at timestamp without time zone,
    responded_at timestamp without time zone
)""",
    """CREATE TABLE public.report_cache (
    id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    simulation_id character varying,
    report_type character varying NOT NULL,
    cta_type character varying NOT NULL,
    status character varying NOT NULL,
    pdf_path character varying,
    content_md character varying,
    error_message character varying,
    created_at timestamp without time zone NOT NULL,
    expires_at timestamp without time zone
)""",
    """CREATE TABLE public.research_objectives (
    id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    description character varying NOT NULL,
    created_by character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    validation_status character varying NOT NULL,
    ai_interpretation json,
    confidence_level integer NOT NULL
)""",
    """CREATE TABLE public.research_objectives_file (
    id character varying NOT NULL,
    research_objectives_id character varying,
    filename character varying,
    original_name character varying NOT NULL,
    content_type character varying,
    size integer,
    uploaded_at timestamp without time zone NOT NULL,
    exploration_id character varying,
    instruction text,
    extracted_context text,
    source_url character varying,
    material_kind character varying,
    relevance_status character varying DEFAULT 'pending'::character varying NOT NULL,
    artifact_category character varying,
    comparison_mode character varying
)""",
    """CREATE TABLE public.studies (
    id integer DEFAULT nextval('studies_id_seq'::regclass) NOT NULL,
    name text NOT NULL,
    created_at timestamp without time zone DEFAULT now()
)""",
    """CREATE TABLE public.subscription_plan (
    id character varying NOT NULL,
    slug character varying NOT NULL,
    name character varying NOT NULL,
    description character varying,
    features character varying DEFAULT '{}'::character varying,
    exploration_limit integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp without time zone NOT NULL
)""",
    """CREATE TABLE public.surveysimulation (
    id character varying NOT NULL,
    workspace_id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    persona_id json,
    persona_sample_sizes json,
    total_sample_size integer NOT NULL,
    simulation_source_id character varying,
    results json,
    narrative json,
    created_by character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    is_download boolean NOT NULL,
    simulation_result json,
    normalized_results jsonb
)""",
    """CREATE TABLE public.test_lab_leads (
    id character varying NOT NULL,
    survey_id character varying NOT NULL,
    name character varying(120) NOT NULL,
    company_name character varying(160) NOT NULL,
    email character varying(255) NOT NULL,
    consent boolean NOT NULL,
    source character varying(80) NOT NULL,
    metadata json,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
)""",
    """CREATE TABLE public.test_lab_profiles (
    id character varying NOT NULL,
    survey_id character varying NOT NULL,
    industry character varying(120),
    scenario character varying(120),
    human_study json,
    synthetic_study json,
    verdict json,
    metadata json,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    geography character varying(512),
    llm_study jsonb
)""",
    """CREATE TABLE public.test_lab_reports (
    id character varying NOT NULL,
    survey_id character varying NOT NULL,
    report json NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
)""",
    """CREATE TABLE public.test_lab_survey_manual (
    survey_id character varying NOT NULL,
    survey_insights jsonb DEFAULT '{}'::jsonb NOT NULL,
    question_insights jsonb DEFAULT '{}'::jsonb NOT NULL,
    source character varying DEFAULT 'manual'::character varying NOT NULL,
    updated_by character varying,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
)""",
    """CREATE TABLE public.test_lab_surveys (
    id character varying NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    total_personas integer,
    total_questions integer,
    accuracy_score double precision,
    confidence_tier character varying(10),
    validation_status character varying(20),
    synthetic_personas json,
    survey_questions json,
    synthetic_responses json,
    real_responses json,
    test_suite_report json,
    created_at timestamp with time zone DEFAULT now(),
    validated_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now(),
    avg_similarity double precision,
    actions_data_points integer,
    neuroscience_data_points integer,
    contextual_layer_data_points integer,
    directional_alignment double precision,
    checks_passed integer,
    avg_prediction_accuracy double precision,
    avg_relationship_strength double precision,
    llm_output jsonb,
    llm_responses jsonb,
    llm_accuracy_score double precision,
    llm_avg_similarity double precision,
    llm_directional_alignment double precision,
    llm_avg_prediction_accuracy double precision,
    llm_avg_relationship_strength double precision,
    llm_checks_passed integer
)""",
    """CREATE TABLE public.test_lab_validation_runs (
    id character varying NOT NULL,
    survey_id character varying NOT NULL,
    overall_accuracy double precision NOT NULL,
    overall_tier character varying(10) NOT NULL,
    question_results json NOT NULL,
    comparison_metadata json,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
)""",
    """CREATE TABLE public.test_lab_verdict (
    survey_id character varying NOT NULL,
    verdict json
)""",
    """CREATE TABLE public.traceability_report (
    id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    ro_traceability json,
    persona_traceability json,
    quant_traceability json,
    qual_traceability json,
    updated_at timestamp without time zone NOT NULL
)""",
    """CREATE TABLE public.traceabilityrecord (
    id character varying NOT NULL,
    workspace_id character varying NOT NULL,
    exploration_id character varying NOT NULL,
    foundation_layer json,
    generation_process json,
    validation_layer json,
    narrative_summary json,
    created_by character varying,
    created_at timestamp without time zone NOT NULL
)""",
    """CREATE TABLE public."user" (
    id character varying NOT NULL,
    full_name character varying,
    email character varying,
    hashed_password character varying,
    user_type character varying,
    role character varying,
    is_verified boolean,
    verification_token character varying,
    verification_expiry timestamp without time zone,
    reset_token character varying,
    reset_token_expiry timestamp without time zone,
    is_active boolean,
    created_at timestamp without time zone,
    last_activity_at timestamp without time zone,
    is_trial boolean DEFAULT true,
    exploration_count integer DEFAULT 0,
    trial_exploration_limit integer DEFAULT 1,
    must_change_password boolean DEFAULT false,
    account_tier character varying DEFAULT 'free'::character varying,
    organization_id character varying,
    first_name character varying DEFAULT ''::character varying NOT NULL,
    last_name character varying DEFAULT ''::character varying NOT NULL,
    phone character varying,
    avatar_url character varying,
    trial_expires_at timestamp without time zone,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone,
    deleted_by character varying
)""",
    """CREATE TABLE public.user_settings (
    id character varying NOT NULL,
    user_id character varying NOT NULL,
    notification_email boolean NOT NULL,
    notification_in_app boolean NOT NULL,
    notification_research_updates boolean NOT NULL,
    notification_billing_alerts boolean NOT NULL,
    notification_product_updates boolean NOT NULL,
    notification_security_alerts boolean NOT NULL,
    language character varying NOT NULL,
    theme character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone
)""",
    """CREATE TABLE public.user_subscription (
    id character varying NOT NULL,
    user_id character varying NOT NULL,
    plan_id character varying NOT NULL,
    status character varying NOT NULL,
    started_at timestamp without time zone NOT NULL,
    expires_at timestamp without time zone,
    cancelled_at timestamp without time zone,
    stripe_subscription_id character varying,
    stripe_customer_id character varying,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone
)""",
    """CREATE TABLE public.users (
    id character varying NOT NULL,
    full_name character varying NOT NULL,
    email character varying NOT NULL,
    hashed_password character varying NOT NULL,
    user_type character varying,
    role character varying,
    is_verified boolean,
    verification_token character varying,
    verification_expiry timestamp without time zone,
    reset_token character varying,
    reset_token_expiry timestamp without time zone,
    is_active boolean,
    is_trial boolean,
    exploration_count integer,
    trial_exploration_limit integer,
    must_change_password boolean,
    account_tier character varying,
    organization_id character varying,
    created_at timestamp without time zone NOT NULL,
    last_activity_at timestamp without time zone,
    is_deleted boolean,
    deleted_at timestamp without time zone,
    deleted_by character varying
)""",
    """CREATE TABLE public.workspace (
    id character varying NOT NULL,
    name character varying NOT NULL,
    description character varying,
    organization_id character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    department_name character varying,
    is_hidden boolean DEFAULT false NOT NULL,
    is_default_personal boolean DEFAULT false NOT NULL
)""",
    """CREATE TABLE public.workspacemember (
    id character varying NOT NULL,
    workspace_id character varying NOT NULL,
    user_id character varying,
    email character varying NOT NULL,
    role character varying NOT NULL,
    token character varying,
    token_expiry timestamp without time zone,
    accepted boolean NOT NULL
)""",
    """CREATE TABLE sync_action.dataset (
    id character varying NOT NULL,
    source_file character varying,
    row_count integer DEFAULT 0 NOT NULL,
    columns jsonb DEFAULT '[]'::jsonb NOT NULL,
    exploration_id character varying,
    uploaded_by character varying,
    uploaded_at timestamp without time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL
)""",
    """CREATE TABLE sync_action.record (
    id character varying NOT NULL,
    dataset_id character varying NOT NULL,
    row_index integer NOT NULL,
    data jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    status character varying DEFAULT 'pending'::character varying NOT NULL,
    workspace_id character varying,
    region character varying,
    year integer,
    source_format character varying,
    subject_key character varying
)""",
    """CREATE TABLE sync_source.content_chunk (
    id character varying NOT NULL,
    document_id character varying NOT NULL,
    chunk_index integer NOT NULL,
    content text NOT NULL,
    content_json jsonb,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    data_type character varying DEFAULT 'document'::character varying NOT NULL,
    content_hash character varying,
    token_count integer,
    embedding_status character varying DEFAULT 'pending'::character varying NOT NULL,
    embedding_model character varying,
    qdrant_point_id character varying,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL
)""",
    """CREATE TABLE sync_source.document (
    id character varying NOT NULL,
    title character varying NOT NULL,
    source_type character varying NOT NULL,
    source_url character varying,
    file_path character varying,
    is_processed boolean DEFAULT false NOT NULL,
    exploration_id character varying,
    uploaded_by character varying,
    uploaded_at timestamp without time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    file_data bytea,
    file_name character varying,
    domain character varying,
    registry_id character varying,
    workspace_id character varying,
    source_group character varying,
    source_keywords jsonb DEFAULT '[]'::jsonb NOT NULL,
    approval_status character varying DEFAULT 'approved'::character varying NOT NULL,
    authority_tier character varying DEFAULT 'user_uploaded'::character varying NOT NULL,
    canonical_url text,
    content_hash character varying,
    quality_score double precision,
    indexed_at timestamp without time zone,
    index_status character varying DEFAULT 'pending'::character varying NOT NULL,
    index_version integer DEFAULT 1 NOT NULL,
    citation_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    allowed_use jsonb DEFAULT '["qual_report", "quant_report", "citation"]'::jsonb NOT NULL
)""",
    """CREATE TABLE sync_source.ke_web_source_cache (
    id character varying NOT NULL,
    exploration_id character varying,
    query_hash character varying NOT NULL,
    sources jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    expires_at timestamp without time zone NOT NULL
)""",
    """CREATE TABLE sync_source.scrape_url (
    id character varying NOT NULL,
    source_document_id character varying,
    source_document_key character varying DEFAULT ''::character varying NOT NULL,
    exploration_id character varying,
    url text NOT NULL,
    domain character varying,
    status character varying DEFAULT 'pending'::character varying NOT NULL,
    failure_reason text,
    failure_category character varying,
    retryable boolean DEFAULT true NOT NULL,
    retry_count integer DEFAULT 0 NOT NULL,
    max_retries integer DEFAULT 3 NOT NULL,
    http_status integer,
    method_used character varying,
    content_chars integer DEFAULT 0 NOT NULL,
    first_seen_at timestamp without time zone DEFAULT now() NOT NULL,
    last_attempt_at timestamp without time zone,
    next_retry_at timestamp without time zone,
    scraped_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
)""",
    """CREATE TABLE sync_source.scrape_url_attempt (
    id character varying NOT NULL,
    scrape_url_id character varying NOT NULL,
    attempt_no integer NOT NULL,
    status character varying NOT NULL,
    method_used character varying,
    http_status integer,
    failure_reason text,
    failure_category character varying,
    retryable boolean DEFAULT true NOT NULL,
    content_chars integer DEFAULT 0 NOT NULL,
    started_at timestamp without time zone DEFAULT now() NOT NULL,
    finished_at timestamp without time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL
)""",
    """CREATE TABLE sync_source.source_registry (
    id character varying NOT NULL,
    name character varying NOT NULL,
    domain character varying,
    source_group character varying,
    base_url text,
    source_kind character varying DEFAULT 'website'::character varying NOT NULL,
    approval_status character varying DEFAULT 'approved'::character varying NOT NULL,
    authority_tier character varying DEFAULT 'curated'::character varying NOT NULL,
    allowed_use jsonb DEFAULT '["qual_report", "quant_report", "citation"]'::jsonb NOT NULL,
    keywords jsonb DEFAULT '[]'::jsonb NOT NULL,
    crawl_policy jsonb DEFAULT '{}'::jsonb NOT NULL,
    owner_workspace_id character varying,
    created_by character varying,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    expires_at timestamp without time zone,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL
)""",
    """CREATE TABLE sync_survey.aggregation (
    id character varying NOT NULL,
    dataset_id character varying NOT NULL,
    results jsonb NOT NULL,
    computed_at timestamp without time zone DEFAULT now() NOT NULL
)""",
    """CREATE TABLE sync_survey.dataset (
    id character varying NOT NULL,
    source_file character varying,
    respondent_count integer DEFAULT 0 NOT NULL,
    question_schema jsonb DEFAULT '[]'::jsonb NOT NULL,
    exploration_id character varying,
    uploaded_by character varying,
    uploaded_at timestamp without time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL
)""",
    """CREATE TABLE sync_survey.response (
    id character varying NOT NULL,
    dataset_id character varying NOT NULL,
    respondent_id character varying,
    answers jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    status character varying DEFAULT 'pending'::character varying NOT NULL,
    workspace_id character varying,
    region character varying,
    year integer,
    source_format character varying,
    subject_key character varying
)""",
)

# Re-establishes the serial ownership link (pg_depend deptype 'a') that makes
# DROP TABLE also drop the sequence. Applied after the tables exist.
SEQUENCE_OWNERS: tuple[str, ...] = (
    'ALTER SEQUENCE public.studies_id_seq OWNED BY public.studies.id',
)

# Primary keys, unique constraints and check constraints. Applied before
# foreign keys so that every referenced key exists by the time FKs are added.
KEYS_AND_CHECKS: tuple[str, ...] = (
    'ALTER TABLE public.artifact_pipeline_run ADD CONSTRAINT artifact_pipeline_run_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.artifact_population_result ADD CONSTRAINT artifact_population_result_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.billing_profile ADD CONSTRAINT billing_profile_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.decision_room_message ADD CONSTRAINT decision_room_message_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.decision_room_session ADD CONSTRAINT decision_room_session_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.dp_analysis ADD CONSTRAINT dp_analysis_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.dp_dataset ADD CONSTRAINT dp_dataset_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.dp_variable ADD CONSTRAINT dp_variable_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.embedded_actions ADD CONSTRAINT embedded_actions_pkey PRIMARY KEY (action_id)',
    'ALTER TABLE public.embedded_chunks ADD CONSTRAINT embedded_chunks_pkey PRIMARY KEY (chunk_id)',
    'ALTER TABLE public.explorations ADD CONSTRAINT explorations_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.interview ADD CONSTRAINT interview_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.interviewfile ADD CONSTRAINT interviewfile_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.interviewquestion ADD CONSTRAINT interviewquestion_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.interviewsection ADD CONSTRAINT interviewsection_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.llm_usage_event ADD CONSTRAINT llm_usage_event_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.market_research_extractions ADD CONSTRAINT market_research_extractions_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.omimessage ADD CONSTRAINT omimessage_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.omisession ADD CONSTRAINT omisession_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.omiworkflowaction ADD CONSTRAINT omiworkflowaction_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.org_settings ADD CONSTRAINT org_settings_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.organization ADD CONSTRAINT organization_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.persona ADD CONSTRAINT persona_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.persona_artifact_response ADD CONSTRAINT persona_artifact_response_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.populationsimulation ADD CONSTRAINT populationsimulation_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.questionnairegenerationjob ADD CONSTRAINT questionnairegenerationjob_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.questionnairegenerationjob ADD CONSTRAINT uq_questionnaire_generation_job_scope UNIQUE (workspace_id, exploration_id, source_key)',
    'ALTER TABLE public.questionnairequestion ADD CONSTRAINT questionnairequestion_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.questionnairequestionasset ADD CONSTRAINT questionnairequestionasset_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.questionnairesection ADD CONSTRAINT questionnairesection_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.rebuttalsession ADD CONSTRAINT rebuttalsession_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.report_cache ADD CONSTRAINT report_cache_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.research_objectives ADD CONSTRAINT research_objectives_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.research_objectives_file ADD CONSTRAINT research_objectives_file_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.studies ADD CONSTRAINT studies_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.subscription_plan ADD CONSTRAINT subscription_plan_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.surveysimulation ADD CONSTRAINT surveysimulation_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.test_lab_leads ADD CONSTRAINT test_lab_leads_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.test_lab_profiles ADD CONSTRAINT test_lab_profiles_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.test_lab_reports ADD CONSTRAINT test_lab_reports_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.test_lab_survey_manual ADD CONSTRAINT test_lab_survey_manual_pkey PRIMARY KEY (survey_id)',
    'ALTER TABLE public.test_lab_surveys ADD CONSTRAINT test_lab_surveys_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.test_lab_validation_runs ADD CONSTRAINT test_lab_validation_runs_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.test_lab_verdict ADD CONSTRAINT test_lab_verdict_pkey PRIMARY KEY (survey_id)',
    'ALTER TABLE public.traceability_report ADD CONSTRAINT traceability_report_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.traceabilityrecord ADD CONSTRAINT traceabilityrecord_pkey PRIMARY KEY (id)',
    'ALTER TABLE public."user" ADD CONSTRAINT user_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.user_settings ADD CONSTRAINT user_settings_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.user_subscription ADD CONSTRAINT user_subscription_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.workspace ADD CONSTRAINT workspace_pkey PRIMARY KEY (id)',
    'ALTER TABLE public.workspacemember ADD CONSTRAINT workspacemember_pkey PRIMARY KEY (id)',
    'ALTER TABLE sync_action.dataset ADD CONSTRAINT dataset_pkey PRIMARY KEY (id)',
    'ALTER TABLE sync_action.record ADD CONSTRAINT record_pkey PRIMARY KEY (id)',
    'ALTER TABLE sync_source.content_chunk ADD CONSTRAINT content_chunk_pkey PRIMARY KEY (id)',
    'ALTER TABLE sync_source.document ADD CONSTRAINT document_pkey PRIMARY KEY (id)',
    'ALTER TABLE sync_source.ke_web_source_cache ADD CONSTRAINT ke_web_source_cache_pkey PRIMARY KEY (id)',
    'ALTER TABLE sync_source.scrape_url ADD CONSTRAINT scrape_url_pkey PRIMARY KEY (id)',
    'ALTER TABLE sync_source.scrape_url_attempt ADD CONSTRAINT scrape_url_attempt_pkey PRIMARY KEY (id)',
    'ALTER TABLE sync_source.scrape_url_attempt ADD CONSTRAINT scrape_url_attempt_scrape_url_id_attempt_no_key UNIQUE (scrape_url_id, attempt_no)',
    'ALTER TABLE sync_source.source_registry ADD CONSTRAINT source_registry_pkey PRIMARY KEY (id)',
    'ALTER TABLE sync_survey.aggregation ADD CONSTRAINT aggregation_dataset_id_key UNIQUE (dataset_id)',
    'ALTER TABLE sync_survey.aggregation ADD CONSTRAINT aggregation_pkey PRIMARY KEY (id)',
    'ALTER TABLE sync_survey.dataset ADD CONSTRAINT dataset_pkey PRIMARY KEY (id)',
    'ALTER TABLE sync_survey.response ADD CONSTRAINT response_pkey PRIMARY KEY (id)',
)

# Foreign keys, with their exact ON DELETE actions. Constraints that are
# currently NOT VALID in the source database are reproduced as NOT VALID here so
# this revision is provably identical to it; revision 0002 validates them.
FOREIGN_KEYS: tuple[str, ...] = (
    'ALTER TABLE public.artifact_pipeline_run ADD CONSTRAINT artifact_pipeline_run_created_by_fkey FOREIGN KEY (created_by) REFERENCES "user"(id)',
    'ALTER TABLE public.artifact_pipeline_run ADD CONSTRAINT artifact_pipeline_run_exploration_id_fkey FOREIGN KEY (exploration_id) REFERENCES explorations(id)',
    'ALTER TABLE public.artifact_pipeline_run ADD CONSTRAINT artifact_pipeline_run_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id)',
    'ALTER TABLE public.artifact_population_result ADD CONSTRAINT artifact_population_result_run_id_fkey FOREIGN KEY (run_id) REFERENCES artifact_pipeline_run(id)',
    'ALTER TABLE public.billing_profile ADD CONSTRAINT billing_profile_org_id_fkey FOREIGN KEY (org_id) REFERENCES organization(id)',
    'ALTER TABLE public.billing_profile ADD CONSTRAINT billing_profile_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(id)',
    'ALTER TABLE public.decision_room_message ADD CONSTRAINT fk_drm_session_id FOREIGN KEY (session_id) REFERENCES decision_room_session(id) ON DELETE CASCADE NOT VALID',
    'ALTER TABLE public.decision_room_session ADD CONSTRAINT fk_drs_created_by FOREIGN KEY (created_by) REFERENCES "user"(id) ON DELETE CASCADE NOT VALID',
    'ALTER TABLE public.decision_room_session ADD CONSTRAINT fk_drs_exploration_id FOREIGN KEY (exploration_id) REFERENCES explorations(id) NOT VALID',
    'ALTER TABLE public.decision_room_session ADD CONSTRAINT fk_drs_workspace_id FOREIGN KEY (workspace_id) REFERENCES workspace(id) NOT VALID',
    'ALTER TABLE public.dp_analysis ADD CONSTRAINT fk_dpa_dataset_id FOREIGN KEY (dataset_id) REFERENCES dp_dataset(id) ON DELETE CASCADE NOT VALID',
    'ALTER TABLE public.dp_dataset ADD CONSTRAINT fk_dpd_created_by FOREIGN KEY (created_by) REFERENCES "user"(id) ON DELETE SET NULL NOT VALID',
    'ALTER TABLE public.dp_dataset ADD CONSTRAINT fk_dpd_exploration_id FOREIGN KEY (exploration_id) REFERENCES explorations(id) NOT VALID',
    'ALTER TABLE public.dp_dataset ADD CONSTRAINT fk_dpd_workspace_id FOREIGN KEY (workspace_id) REFERENCES workspace(id) NOT VALID',
    'ALTER TABLE public.dp_variable ADD CONSTRAINT fk_dpv_dataset_id FOREIGN KEY (dataset_id) REFERENCES dp_dataset(id) ON DELETE CASCADE NOT VALID',
    'ALTER TABLE public.explorations ADD CONSTRAINT explorations_created_by_fkey FOREIGN KEY (created_by) REFERENCES "user"(id)',
    'ALTER TABLE public.explorations ADD CONSTRAINT explorations_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id)',
    'ALTER TABLE public.explorations ADD CONSTRAINT fk_explorations_deleted_by FOREIGN KEY (deleted_by) REFERENCES "user"(id) ON DELETE SET NULL NOT VALID',
    'ALTER TABLE public.explorations ADD CONSTRAINT fk_explorations_updated_by FOREIGN KEY (updated_by) REFERENCES "user"(id) ON DELETE SET NULL NOT VALID',
    'ALTER TABLE public.interview ADD CONSTRAINT interview_created_by_fkey FOREIGN KEY (created_by) REFERENCES "user"(id)',
    'ALTER TABLE public.interview ADD CONSTRAINT interview_exploration_id_fkey FOREIGN KEY (exploration_id) REFERENCES explorations(id)',
    'ALTER TABLE public.interview ADD CONSTRAINT interview_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES persona(id) ON DELETE SET NULL NOT VALID',
    'ALTER TABLE public.interview ADD CONSTRAINT interview_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id)',
    'ALTER TABLE public.interviewfile ADD CONSTRAINT interviewfile_interview_id_fkey FOREIGN KEY (interview_id) REFERENCES interview(id)',
    'ALTER TABLE public.interviewquestion ADD CONSTRAINT interviewquestion_created_by_fkey FOREIGN KEY (created_by) REFERENCES "user"(id)',
    'ALTER TABLE public.interviewquestion ADD CONSTRAINT interviewquestion_section_id_fkey FOREIGN KEY (section_id) REFERENCES interviewsection(id)',
    'ALTER TABLE public.interviewsection ADD CONSTRAINT interviewsection_created_by_fkey FOREIGN KEY (created_by) REFERENCES "user"(id)',
    'ALTER TABLE public.interviewsection ADD CONSTRAINT interviewsection_exploration_id_fkey FOREIGN KEY (exploration_id) REFERENCES explorations(id)',
    'ALTER TABLE public.interviewsection ADD CONSTRAINT interviewsection_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id)',
    'ALTER TABLE public.omimessage ADD CONSTRAINT omimessage_session_id_fkey FOREIGN KEY (session_id) REFERENCES omisession(id)',
    'ALTER TABLE public.omisession ADD CONSTRAINT omisession_exploration_id_fkey FOREIGN KEY (exploration_id) REFERENCES explorations(id)',
    'ALTER TABLE public.omisession ADD CONSTRAINT omisession_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id)',
    'ALTER TABLE public.omisession ADD CONSTRAINT omisession_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(id)',
    'ALTER TABLE public.omisession ADD CONSTRAINT omisession_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id)',
    'ALTER TABLE public.omiworkflowaction ADD CONSTRAINT omiworkflowaction_session_id_fkey FOREIGN KEY (session_id) REFERENCES omisession(id)',
    'ALTER TABLE public.org_settings ADD CONSTRAINT org_settings_org_id_fkey FOREIGN KEY (org_id) REFERENCES organization(id)',
    'ALTER TABLE public.organization ADD CONSTRAINT organization_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES "user"(id)',
    'ALTER TABLE public.persona ADD CONSTRAINT persona_exploration_id_fkey FOREIGN KEY (exploration_id) REFERENCES explorations(id)',
    'ALTER TABLE public.persona ADD CONSTRAINT persona_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id)',
    'ALTER TABLE public.persona_artifact_response ADD CONSTRAINT persona_artifact_response_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES persona(id) ON DELETE CASCADE NOT VALID',
    'ALTER TABLE public.persona_artifact_response ADD CONSTRAINT persona_artifact_response_run_id_fkey FOREIGN KEY (run_id) REFERENCES artifact_pipeline_run(id)',
    'ALTER TABLE public.populationsimulation ADD CONSTRAINT populationsimulation_created_by_fkey FOREIGN KEY (created_by) REFERENCES "user"(id)',
    'ALTER TABLE public.populationsimulation ADD CONSTRAINT populationsimulation_exploration_id_fkey FOREIGN KEY (exploration_id) REFERENCES explorations(id)',
    'ALTER TABLE public.populationsimulation ADD CONSTRAINT populationsimulation_research_objective_id_fkey FOREIGN KEY (research_objective_id) REFERENCES research_objectives(id)',
    'ALTER TABLE public.populationsimulation ADD CONSTRAINT populationsimulation_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id)',
    'ALTER TABLE public.questionnairegenerationjob ADD CONSTRAINT questionnairegenerationjob_created_by_fkey FOREIGN KEY (created_by) REFERENCES "user"(id)',
    'ALTER TABLE public.questionnairegenerationjob ADD CONSTRAINT questionnairegenerationjob_exploration_id_fkey FOREIGN KEY (exploration_id) REFERENCES explorations(id)',
    'ALTER TABLE public.questionnairegenerationjob ADD CONSTRAINT questionnairegenerationjob_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id)',
    'ALTER TABLE public.questionnairequestion ADD CONSTRAINT questionnairequestion_created_by_fkey FOREIGN KEY (created_by) REFERENCES "user"(id)',
    'ALTER TABLE public.questionnairequestion ADD CONSTRAINT questionnairequestion_section_id_fkey FOREIGN KEY (section_id) REFERENCES questionnairesection(id)',
    'ALTER TABLE public.questionnairequestionasset ADD CONSTRAINT questionnairequestionasset_exploration_id_fkey FOREIGN KEY (exploration_id) REFERENCES explorations(id)',
    'ALTER TABLE public.questionnairequestionasset ADD CONSTRAINT questionnairequestionasset_question_id_fkey FOREIGN KEY (question_id) REFERENCES questionnairequestion(id)',
    'ALTER TABLE public.questionnairequestionasset ADD CONSTRAINT questionnairequestionasset_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES "user"(id)',
    'ALTER TABLE public.questionnairequestionasset ADD CONSTRAINT questionnairequestionasset_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id)',
    'ALTER TABLE public.questionnairesection ADD CONSTRAINT questionnairesection_created_by_fkey FOREIGN KEY (created_by) REFERENCES "user"(id)',
    'ALTER TABLE public.questionnairesection ADD CONSTRAINT questionnairesection_exploration_id_fkey FOREIGN KEY (exploration_id) REFERENCES explorations(id)',
    'ALTER TABLE public.questionnairesection ADD CONSTRAINT questionnairesection_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id)',
    'ALTER TABLE public.rebuttalsession ADD CONSTRAINT rebuttalsession_created_by_fkey FOREIGN KEY (created_by) REFERENCES "user"(id)',
    'ALTER TABLE public.rebuttalsession ADD CONSTRAINT rebuttalsession_exploration_id_fkey FOREIGN KEY (exploration_id) REFERENCES explorations(id)',
    'ALTER TABLE public.rebuttalsession ADD CONSTRAINT rebuttalsession_question_id_fkey FOREIGN KEY (question_id) REFERENCES questionnairequestion(id)',
    'ALTER TABLE public.rebuttalsession ADD CONSTRAINT rebuttalsession_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id)',
    'ALTER TABLE public.research_objectives ADD CONSTRAINT research_objectives_created_by_fkey FOREIGN KEY (created_by) REFERENCES "user"(id)',
    'ALTER TABLE public.research_objectives ADD CONSTRAINT research_objectives_exploration_id_fkey FOREIGN KEY (exploration_id) REFERENCES explorations(id)',
    'ALTER TABLE public.research_objectives_file ADD CONSTRAINT fk_research_objectives_file_exploration_id FOREIGN KEY (exploration_id) REFERENCES explorations(id) ON DELETE CASCADE NOT VALID',
    'ALTER TABLE public.research_objectives_file ADD CONSTRAINT research_objectives_file_research_objectives_id_fkey FOREIGN KEY (research_objectives_id) REFERENCES research_objectives(id)',
    'ALTER TABLE public.surveysimulation ADD CONSTRAINT surveysimulation_created_by_fkey FOREIGN KEY (created_by) REFERENCES "user"(id)',
    'ALTER TABLE public.surveysimulation ADD CONSTRAINT surveysimulation_exploration_id_fkey FOREIGN KEY (exploration_id) REFERENCES explorations(id)',
    'ALTER TABLE public.surveysimulation ADD CONSTRAINT surveysimulation_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id)',
    'ALTER TABLE public.traceability_report ADD CONSTRAINT traceability_report_exploration_id_fkey FOREIGN KEY (exploration_id) REFERENCES explorations(id)',
    'ALTER TABLE public.traceabilityrecord ADD CONSTRAINT traceabilityrecord_created_by_fkey FOREIGN KEY (created_by) REFERENCES "user"(id)',
    'ALTER TABLE public.traceabilityrecord ADD CONSTRAINT traceabilityrecord_exploration_id_fkey FOREIGN KEY (exploration_id) REFERENCES explorations(id)',
    'ALTER TABLE public.traceabilityrecord ADD CONSTRAINT traceabilityrecord_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id)',
    'ALTER TABLE public."user" ADD CONSTRAINT fk_user_deleted_by FOREIGN KEY (deleted_by) REFERENCES "user"(id) ON DELETE SET NULL NOT VALID',
    'ALTER TABLE public."user" ADD CONSTRAINT user_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE SET NULL',
    'ALTER TABLE public.user_settings ADD CONSTRAINT user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(id)',
    'ALTER TABLE public.user_subscription ADD CONSTRAINT user_subscription_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES subscription_plan(id)',
    'ALTER TABLE public.user_subscription ADD CONSTRAINT user_subscription_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(id)',
    'ALTER TABLE public.workspace ADD CONSTRAINT workspace_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id)',
    'ALTER TABLE public.workspacemember ADD CONSTRAINT workspacemember_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(id)',
    'ALTER TABLE public.workspacemember ADD CONSTRAINT workspacemember_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspace(id)',
    'ALTER TABLE sync_action.record ADD CONSTRAINT record_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES sync_action.dataset(id) ON DELETE CASCADE',
    'ALTER TABLE sync_source.content_chunk ADD CONSTRAINT content_chunk_document_id_fkey FOREIGN KEY (document_id) REFERENCES sync_source.document(id) ON DELETE CASCADE',
    'ALTER TABLE sync_source.scrape_url ADD CONSTRAINT scrape_url_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES sync_source.document(id) ON DELETE CASCADE',
    'ALTER TABLE sync_source.scrape_url_attempt ADD CONSTRAINT scrape_url_attempt_scrape_url_id_fkey FOREIGN KEY (scrape_url_id) REFERENCES sync_source.scrape_url(id) ON DELETE CASCADE',
    'ALTER TABLE sync_survey.aggregation ADD CONSTRAINT aggregation_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES sync_survey.dataset(id) ON DELETE CASCADE',
    'ALTER TABLE sync_survey.response ADD CONSTRAINT response_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES sync_survey.dataset(id) ON DELETE CASCADE',
)

# Explicit indexes only. Indexes backing a PRIMARY KEY or UNIQUE constraint are
# created by the constraint itself and are not repeated.
INDEXES: tuple[str, ...] = (
    'CREATE INDEX ix_artifact_pipeline_run_exploration_id ON public.artifact_pipeline_run USING btree (exploration_id)',
    'CREATE INDEX ix_artifact_pipeline_run_status ON public.artifact_pipeline_run USING btree (status)',
    'CREATE UNIQUE INDEX ix_artifact_population_result_run_id ON public.artifact_population_result USING btree (run_id)',
    'CREATE INDEX ix_billing_profile_org_id ON public.billing_profile USING btree (org_id)',
    'CREATE INDEX ix_billing_profile_user_id ON public.billing_profile USING btree (user_id)',
    'CREATE UNIQUE INDEX ux_billing_profile_user_id ON public.billing_profile USING btree (user_id)',
    'CREATE INDEX ix_decision_room_message_role ON public.decision_room_message USING btree (role)',
    'CREATE INDEX ix_decision_room_message_session_id ON public.decision_room_message USING btree (session_id)',
    'CREATE INDEX ix_drm_role ON public.decision_room_message USING btree (role)',
    'CREATE INDEX ix_drm_session_seq ON public.decision_room_message USING btree (session_id, sequence_num)',
    'CREATE INDEX ix_decision_room_session_created_by ON public.decision_room_session USING btree (created_by)',
    'CREATE INDEX ix_decision_room_session_exploration_id ON public.decision_room_session USING btree (exploration_id)',
    'CREATE INDEX ix_decision_room_session_flow ON public.decision_room_session USING btree (flow)',
    'CREATE INDEX ix_decision_room_session_status ON public.decision_room_session USING btree (status)',
    'CREATE INDEX ix_decision_room_session_workspace_id ON public.decision_room_session USING btree (workspace_id)',
    'CREATE INDEX ix_drs_created_by ON public.decision_room_session USING btree (created_by)',
    'CREATE INDEX ix_drs_exploration_id ON public.decision_room_session USING btree (exploration_id)',
    'CREATE INDEX ix_drs_flow ON public.decision_room_session USING btree (flow)',
    'CREATE INDEX ix_drs_status ON public.decision_room_session USING btree (status)',
    'CREATE INDEX ix_drs_workspace_id ON public.decision_room_session USING btree (workspace_id)',
    'CREATE INDEX ix_dpa_dataset_type ON public.dp_analysis USING btree (dataset_id, analysis_type)',
    'CREATE INDEX ix_dp_dataset_created_by ON public.dp_dataset USING btree (created_by)',
    'CREATE INDEX ix_dp_dataset_exploration_id ON public.dp_dataset USING btree (exploration_id)',
    'CREATE INDEX ix_dp_dataset_status ON public.dp_dataset USING btree (status)',
    'CREATE INDEX ix_dp_dataset_workspace_id ON public.dp_dataset USING btree (workspace_id)',
    'CREATE INDEX ix_dpv_dataset_position ON public.dp_variable USING btree (dataset_id, "position")',
    'CREATE INDEX idx_embedded_actions_namespace ON public.embedded_actions USING btree (namespace)',
    'CREATE INDEX idx_embedded_chunks_namespace ON public.embedded_chunks USING btree (namespace)',
    'CREATE INDEX ix_explorations_is_deleted ON public.explorations USING btree (is_deleted)',
    'CREATE INDEX ix_explorations_workspace_id ON public.explorations USING btree (workspace_id)',
    'CREATE INDEX ix_interview_session_group_id ON public.interview USING btree (session_group_id)',
    'CREATE INDEX ix_interviewsection_is_download ON public.interviewsection USING btree (is_download)',
    'CREATE INDEX ix_llm_usage_event_created_at ON public.llm_usage_event USING btree (created_at)',
    'CREATE INDEX ix_llm_usage_event_exploration_id ON public.llm_usage_event USING btree (exploration_id)',
    'CREATE INDEX ix_llm_usage_event_model ON public.llm_usage_event USING btree (model)',
    'CREATE INDEX ix_llm_usage_event_persona_id ON public.llm_usage_event USING btree (persona_id)',
    'CREATE INDEX ix_llm_usage_event_provider ON public.llm_usage_event USING btree (provider)',
    'CREATE INDEX ix_llm_usage_event_request_id ON public.llm_usage_event USING btree (request_id)',
    'CREATE INDEX ix_llm_usage_event_session_id ON public.llm_usage_event USING btree (session_id)',
    'CREATE INDEX ix_llm_usage_event_stage ON public.llm_usage_event USING btree (stage)',
    'CREATE INDEX ix_llm_usage_event_workspace_id ON public.llm_usage_event USING btree (workspace_id)',
    'CREATE INDEX ix_lue_created_at ON public.llm_usage_event USING btree (created_at)',
    'CREATE INDEX ix_lue_exploration_id ON public.llm_usage_event USING btree (exploration_id)',
    'CREATE INDEX ix_lue_model ON public.llm_usage_event USING btree (model)',
    'CREATE INDEX ix_lue_persona_id ON public.llm_usage_event USING btree (persona_id)',
    'CREATE INDEX ix_lue_provider ON public.llm_usage_event USING btree (provider)',
    'CREATE INDEX ix_lue_request_id ON public.llm_usage_event USING btree (request_id)',
    'CREATE INDEX ix_lue_session_id ON public.llm_usage_event USING btree (session_id)',
    'CREATE INDEX ix_lue_stage ON public.llm_usage_event USING btree (stage)',
    'CREATE INDEX ix_lue_workspace_id ON public.llm_usage_event USING btree (workspace_id)',
    'CREATE INDEX ix_market_research_extractions_survey_id ON public.market_research_extractions USING btree (survey_id)',
    'CREATE INDEX ix_org_settings_org_id ON public.org_settings USING btree (org_id)',
    'CREATE UNIQUE INDEX ux_org_settings_org_id ON public.org_settings USING btree (org_id)',
    'CREATE INDEX ix_persona_artifact_response_persona_id ON public.persona_artifact_response USING btree (persona_id)',
    'CREATE INDEX ix_persona_artifact_response_run_id ON public.persona_artifact_response USING btree (run_id)',
    'CREATE INDEX ix_persona_artifact_response_status ON public.persona_artifact_response USING btree (status)',
    'CREATE INDEX ix_populationsimulation_exploration_id ON public.populationsimulation USING btree (exploration_id)',
    'CREATE INDEX ix_populationsimulation_research_objective_id ON public.populationsimulation USING btree (research_objective_id)',
    'CREATE INDEX ix_populationsimulation_workspace_id ON public.populationsimulation USING btree (workspace_id)',
    'CREATE INDEX ix_questionnairegenerationjob_created_by ON public.questionnairegenerationjob USING btree (created_by)',
    'CREATE INDEX ix_questionnairegenerationjob_exploration_id ON public.questionnairegenerationjob USING btree (exploration_id)',
    'CREATE INDEX ix_questionnairegenerationjob_simulation_id ON public.questionnairegenerationjob USING btree (simulation_id)',
    'CREATE INDEX ix_questionnairegenerationjob_source_key ON public.questionnairegenerationjob USING btree (source_key)',
    'CREATE INDEX ix_questionnairegenerationjob_status ON public.questionnairegenerationjob USING btree (status)',
    'CREATE INDEX ix_questionnairegenerationjob_workspace_id ON public.questionnairegenerationjob USING btree (workspace_id)',
    'CREATE INDEX ix_questionnairequestion_order_index ON public.questionnairequestion USING btree (order_index)',
    'CREATE INDEX ix_questionnairequestion_question_key ON public.questionnairequestion USING btree (question_key)',
    'CREATE INDEX ix_questionnairequestion_question_type ON public.questionnairequestion USING btree (question_type)',
    'CREATE INDEX ix_questionnairequestionasset_asset_type ON public.questionnairequestionasset USING btree (asset_type)',
    'CREATE INDEX ix_questionnairequestionasset_exploration_id ON public.questionnairequestionasset USING btree (exploration_id)',
    'CREATE INDEX ix_questionnairequestionasset_question_id ON public.questionnairequestionasset USING btree (question_id)',
    'CREATE INDEX ix_questionnairequestionasset_uploaded_by ON public.questionnairequestionasset USING btree (uploaded_by)',
    'CREATE INDEX ix_questionnairequestionasset_workspace_id ON public.questionnairequestionasset USING btree (workspace_id)',
    'CREATE INDEX ix_questionnairesection_order_index ON public.questionnairesection USING btree (order_index)',
    'CREATE INDEX ix_questionnairesection_parent_section_id ON public.questionnairesection USING btree (parent_section_id)',
    'CREATE INDEX ix_questionnairesection_simulation_id ON public.questionnairesection USING btree (simulation_id)',
    'CREATE INDEX ix_rebuttalsession_created_by ON public.rebuttalsession USING btree (created_by)',
    'CREATE INDEX ix_rebuttalsession_exploration_id ON public.rebuttalsession USING btree (exploration_id)',
    'CREATE INDEX ix_rebuttalsession_persona_id ON public.rebuttalsession USING btree (persona_id)',
    'CREATE INDEX ix_rebuttalsession_question_id ON public.rebuttalsession USING btree (question_id)',
    'CREATE INDEX ix_rebuttalsession_simulation_id ON public.rebuttalsession USING btree (simulation_id)',
    'CREATE INDEX ix_rebuttalsession_workspace_id ON public.rebuttalsession USING btree (workspace_id)',
    'CREATE INDEX idx_report_cache_lookup ON public.report_cache USING btree (exploration_id, simulation_id, cta_type)',
    'CREATE INDEX ix_report_cache_cta_type ON public.report_cache USING btree (cta_type)',
    'CREATE INDEX ix_report_cache_exploration_id ON public.report_cache USING btree (exploration_id)',
    'CREATE INDEX ix_report_cache_simulation_id ON public.report_cache USING btree (simulation_id)',
    'CREATE UNIQUE INDEX uq_report_cache_qual ON public.report_cache USING btree (exploration_id, cta_type) WHERE (simulation_id IS NULL)',
    'CREATE UNIQUE INDEX uq_report_cache_quant ON public.report_cache USING btree (exploration_id, simulation_id, cta_type) WHERE (simulation_id IS NOT NULL)',
    'CREATE INDEX ix_research_objectives_file_exploration_id ON public.research_objectives_file USING btree (exploration_id)',
    'CREATE UNIQUE INDEX ix_subscription_plan_slug ON public.subscription_plan USING btree (slug)',
    'CREATE INDEX ix_surveysimulation_exploration_id ON public.surveysimulation USING btree (exploration_id)',
    'CREATE INDEX ix_surveysimulation_is_download ON public.surveysimulation USING btree (is_download)',
    'CREATE INDEX ix_surveysimulation_workspace_id ON public.surveysimulation USING btree (workspace_id)',
    'CREATE UNIQUE INDEX ux_surveysimulation_simulation_source_id ON public.surveysimulation USING btree (simulation_source_id) WHERE (simulation_source_id IS NOT NULL)',
    'CREATE INDEX ix_test_lab_leads_email ON public.test_lab_leads USING btree (email)',
    'CREATE INDEX ix_test_lab_leads_survey_id ON public.test_lab_leads USING btree (survey_id)',
    'CREATE INDEX ix_test_lab_profiles_industry ON public.test_lab_profiles USING btree (industry)',
    'CREATE INDEX ix_test_lab_profiles_scenario ON public.test_lab_profiles USING btree (scenario)',
    'CREATE UNIQUE INDEX ix_test_lab_profiles_survey_id ON public.test_lab_profiles USING btree (survey_id)',
    'CREATE UNIQUE INDEX ix_test_lab_reports_survey_id ON public.test_lab_reports USING btree (survey_id)',
    'CREATE INDEX ix_test_lab_surveys_title ON public.test_lab_surveys USING btree (title)',
    'CREATE INDEX ix_test_lab_validation_runs_survey_id ON public.test_lab_validation_runs USING btree (survey_id)',
    'CREATE UNIQUE INDEX ix_traceability_report_exploration_id ON public.traceability_report USING btree (exploration_id)',
    'CREATE UNIQUE INDEX ix_user_email ON public."user" USING btree (email)',
    'CREATE INDEX ix_user_is_deleted ON public."user" USING btree (is_deleted)',
    'CREATE INDEX ix_user_organization_id ON public."user" USING btree (organization_id)',
    'CREATE INDEX ix_user_settings_user_id ON public.user_settings USING btree (user_id)',
    'CREATE UNIQUE INDEX ux_user_settings_user_id ON public.user_settings USING btree (user_id)',
    'CREATE INDEX ix_user_subscription_plan_id ON public.user_subscription USING btree (plan_id)',
    'CREATE INDEX ix_user_subscription_status ON public.user_subscription USING btree (status)',
    'CREATE INDEX ix_user_subscription_user_id ON public.user_subscription USING btree (user_id)',
    'CREATE UNIQUE INDEX ix_users_email ON public.users USING btree (email)',
    'CREATE INDEX ix_workspace_is_default_personal ON public.workspace USING btree (is_default_personal)',
    'CREATE INDEX idx_sync_action_record_data ON sync_action.record USING gin (data)',
    'CREATE INDEX idx_sync_action_record_dataset ON sync_action.record USING btree (dataset_id)',
    'CREATE INDEX idx_sync_action_record_status ON sync_action.record USING btree (status)',
    'CREATE INDEX idx_sync_action_record_workspace ON sync_action.record USING btree (workspace_id)',
    'CREATE INDEX idx_sync_source_chunk_content_hash ON sync_source.content_chunk USING btree (content_hash)',
    'CREATE INDEX idx_sync_source_chunk_content_json ON sync_source.content_chunk USING gin (content_json)',
    'CREATE INDEX idx_sync_source_chunk_data_type ON sync_source.content_chunk USING btree (data_type)',
    'CREATE INDEX idx_sync_source_chunk_doc_type_order ON sync_source.content_chunk USING btree (document_id, data_type, chunk_index, created_at)',
    'CREATE INDEX idx_sync_source_chunk_document ON sync_source.content_chunk USING btree (document_id)',
    'CREATE INDEX idx_sync_source_chunk_embedding_status ON sync_source.content_chunk USING btree (embedding_status)',
    "CREATE INDEX idx_sync_source_chunk_fts ON sync_source.content_chunk USING gin (to_tsvector('simple'::regconfig, COALESCE(content, ''::text)))",
    'CREATE INDEX idx_sync_source_document_approval ON sync_source.document USING btree (approval_status)',
    'CREATE INDEX idx_sync_source_document_domain ON sync_source.document USING btree (domain)',
    'CREATE INDEX idx_sync_source_document_group ON sync_source.document USING btree (source_group)',
    'CREATE INDEX idx_sync_source_document_registry ON sync_source.document USING btree (registry_id)',
    'CREATE INDEX idx_ke_web_source_cache_expires ON sync_source.ke_web_source_cache USING btree (expires_at)',
    'CREATE UNIQUE INDEX ux_ke_web_source_cache_lookup ON sync_source.ke_web_source_cache USING btree (exploration_id, query_hash)',
    'CREATE INDEX idx_sync_source_scrape_url_domain ON sync_source.scrape_url USING btree (domain)',
    "CREATE INDEX idx_sync_source_scrape_url_retry ON sync_source.scrape_url USING btree (next_retry_at, retry_count) WHERE ((retryable = true) AND ((status)::text = ANY ((ARRAY['failed'::character varying, 'low_quality'::character varying])::text[])) AND (retry_count < max_retries))",
    'CREATE INDEX idx_sync_source_scrape_url_status ON sync_source.scrape_url USING btree (status)',
    'CREATE UNIQUE INDEX ux_sync_source_scrape_url_doc_url ON sync_source.scrape_url USING btree (source_document_key, url)',
    'CREATE INDEX idx_sync_source_scrape_attempt_url ON sync_source.scrape_url_attempt USING btree (scrape_url_id)',
    'CREATE INDEX idx_sync_source_registry_approval ON sync_source.source_registry USING btree (approval_status)',
    'CREATE INDEX idx_sync_source_registry_domain ON sync_source.source_registry USING btree (domain)',
    'CREATE INDEX idx_sync_source_registry_group ON sync_source.source_registry USING btree (source_group)',
    'CREATE UNIQUE INDEX ux_sync_survey_aggregation_dataset_id ON sync_survey.aggregation USING btree (dataset_id)',
    'CREATE INDEX idx_sync_survey_response_dataset ON sync_survey.response USING btree (dataset_id)',
    'CREATE INDEX idx_sync_survey_response_status ON sync_survey.response USING btree (status)',
    'CREATE INDEX idx_sync_survey_response_workspace ON sync_survey.response USING btree (workspace_id)',
)

# Complete CREATE OR REPLACE FUNCTION statements from pg_get_functiondef().
# Emitted before triggers, which reference them.
FUNCTIONS: tuple[str, ...] = (
    """CREATE OR REPLACE FUNCTION public.set_test_lab_survey_manual_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$""",
)

# Trigger definitions from pg_get_triggerdef(). Foreign-key enforcement
# triggers are excluded — those are created implicitly with their constraint.
TRIGGERS: tuple[str, ...] = (
    'CREATE TRIGGER set_test_lab_survey_manual_updated_at BEFORE UPDATE ON public.test_lab_survey_manual FOR EACH ROW EXECUTE FUNCTION set_test_lab_survey_manual_updated_at()',
)

# Drop order for downgrade(). CASCADE handles inter-table dependencies.
TABLES: tuple[str, ...] = ('public.artifact_pipeline_run', 'public.artifact_population_result', 'public.billing_profile', 'public.decision_room_message', 'public.decision_room_session', 'public.dp_analysis', 'public.dp_dataset', 'public.dp_variable', 'public.embedded_actions', 'public.embedded_chunks', 'public.explorations', 'public.interview', 'public.interviewfile', 'public.interviewquestion', 'public.interviewsection', 'public.llm_usage_event', 'public.market_research_extractions', 'public.omimessage', 'public.omisession', 'public.omiworkflowaction', 'public.org_settings', 'public.organization', 'public.persona', 'public.persona_artifact_response', 'public.populationsimulation', 'public.questionnairegenerationjob', 'public.questionnairequestion', 'public.questionnairequestionasset', 'public.questionnairesection', 'public.rebuttalsession', 'public.report_cache', 'public.research_objectives', 'public.research_objectives_file', 'public.studies', 'public.subscription_plan', 'public.surveysimulation', 'public.test_lab_leads', 'public.test_lab_profiles', 'public.test_lab_reports', 'public.test_lab_survey_manual', 'public.test_lab_surveys', 'public.test_lab_validation_runs', 'public.test_lab_verdict', 'public.traceability_report', 'public.traceabilityrecord', 'public.user', 'public.user_settings', 'public.user_subscription', 'public.users', 'public.workspace', 'public.workspacemember', 'sync_action.dataset', 'sync_action.record', 'sync_source.content_chunk', 'sync_source.document', 'sync_source.ke_web_source_cache', 'sync_source.scrape_url', 'sync_source.scrape_url_attempt', 'sync_source.source_registry', 'sync_survey.aggregation', 'sync_survey.dataset', 'sync_survey.response')
FUNCTION_NAMES: tuple[str, ...] = ('public.set_test_lab_survey_manual_updated_at',)


def upgrade() -> None:
    for schema in SCHEMAS:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
    for statement in SEQUENCES:
        op.execute(statement)
    for statement in CREATE_TABLES:
        op.execute(statement)
    for statement in SEQUENCE_OWNERS:
        op.execute(statement)
    for statement in KEYS_AND_CHECKS:
        op.execute(statement)
    for statement in FOREIGN_KEYS:
        op.execute(statement)
    for statement in INDEXES:
        op.execute(statement)
    for statement in FUNCTIONS:
        op.execute(statement)
    for statement in TRIGGERS:
        op.execute(statement)


def downgrade() -> None:
    """Drop everything this revision created.

    Only ever reachable on a database this revision actually built — a stamped
    database would find nothing to drop and is not expected to downgrade past
    the baseline. CASCADE is required because foreign keys span tables.
    """
    # Tables first: CASCADE takes their triggers and any sequence they own.
    for qualified_name in reversed(TABLES):
        schema, table = qualified_name.split(".", 1)
        op.execute(f'DROP TABLE IF EXISTS "{schema}"."{table}" CASCADE')
    # Functions are not owned by any table, so they must be dropped explicitly.
    for function_name in FUNCTION_NAMES:
        schema, name = function_name.split(".", 1)
        op.execute(f'DROP FUNCTION IF EXISTS "{schema}"."{name}"() CASCADE')
    # Any sequence not owned by a dropped column still exists at this point.
    for statement in SEQUENCES:
        name = statement.split()[2]
        op.execute(f"DROP SEQUENCE IF EXISTS {name} CASCADE")
    for schema in SCHEMAS:
        op.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
