import React from 'react';
import './TermsAndPoliciesStyle.css';

// ── Types ─────────────────────────────────────────────────────────────────────

interface TermsSection {
  heading: string;
  paragraphs: string[];
}

// ── Static content (replace with API fetch if needed) ─────────────────────────

const ACCEPTED_DATE = '12 Jan 2026';

const TERMS_INTRO =
  'SYNTHETIC PEOPLE Terms of Service & Privacy Policy Effective Date: 19 March 2026 Operated by Syntera Solutions Pvt Ltd';

const TERMS_SECTIONS: TermsSection[] = [
  {
    heading: '1. Definitions',
    paragraphs: [
      '"Platform" means the Synthetic People website, Test Studio application, APIs, research workflows, output reports, persona models, and all related digital infrastructure operated by the Company.',
      '"User" means any individual or entity that accesses, registers on, or interacts with the Platform, whether through the Free Trial Pack, a paid subscription, or a direct enterprise arrangement.',
      '"Synthetic People" or "Synthetic Personas" means the AI-generated behavioural simulations produced by the Platform, grounded in aggregated consumer action data, neuroscience-aligned signals, and historical research.',
      '"Research Output" means any report, persona summary, qualitative exploration result, quantitative study finding, traceability log, or other deliverable generated by the Platform in response to a User\'s research objective.',
      '"First-Party Data" means proprietary data voluntarily uploaded by a User to enrich research personalisation on the Pro Pack tier.',
      '"Subscription" means a paid or free-tier access arrangement as described in the Pricing section of the Platform.',
    ],
  },
  {
    heading: '2. Acceptance of Terms',
    paragraphs: [
      'By accessing or using the Platform, you confirm that you have read, understood, and agree to be bound by these Terms of Service and our Privacy Policy.',
      'If you are using the Platform on behalf of an organisation, you represent that you have the authority to bind that organisation to these terms.',
      'We reserve the right to update these terms at any time. Continued use of the Platform after changes constitutes acceptance of the revised terms.',
    ],
  },
  {
    heading: '3. Privacy & Data',
    paragraphs: [
      'We collect and process personal data as described in our Privacy Policy. By using the Platform, you consent to such collection and processing.',
      'Research Outputs generated by the Platform are owned by the User who initiated the research, subject to the restrictions outlined in these terms.',
      'We do not sell your personal data to third parties. Aggregated, anonymised usage data may be used to improve Platform functionality.',
    ],
  },
  {
    heading: '4. Intellectual Property',
    paragraphs: [
      'The Platform, including all software, algorithms, designs, and underlying models, is the exclusive property of Syntera Solutions Pvt Ltd.',
      'Users retain ownership of their First-Party Data and the Research Outputs they generate, subject to our licence to use anonymised versions to improve the Platform.',
      'You may not reverse-engineer, decompile, or attempt to extract the source code of any part of the Platform.',
    ],
  },
  {
    heading: '5. Limitation of Liability',
    paragraphs: [
      'The Platform is provided "as is" without warranties of any kind, express or implied, including but not limited to merchantability or fitness for a particular purpose.',
      'Syntera Solutions Pvt Ltd shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Platform.',
      'Our total liability to you for any claims arising under these terms shall not exceed the fees paid by you in the twelve months preceding the claim.',
    ],
  },
];

// ── Component ─────────────────────────────────────────────────────────────────

const TermsAndPolicies: React.FC = () => (
  <div className="tp-page">
    <p className="tp-accepted">You accepted on {ACCEPTED_DATE}</p>

    <div className="tp-scroll-area">
      <p className="tp-intro">{TERMS_INTRO}</p>

      {TERMS_SECTIONS.map((section) => (
        <div key={section.heading} className="tp-section">
          <h4 className="tp-section-heading">{section.heading}</h4>
          {section.paragraphs.map((para, i) => (
            <p key={i} className="tp-para">{para}</p>
          ))}
        </div>
      ))}
    </div>
  </div>
);

export default TermsAndPolicies;